# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


AdmissionregistrationV1beta1ServiceReferenceDict = TypedDict(
    "AdmissionregistrationV1beta1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "path": str,
        "port": int,
    },
    total=False,
)