# Code generated by `typeddictgen`. DO NOT EDIT.
"""AdmissionregistrationV1beta1WebhookClientConfigDict generated type."""
from typing import TypedDict

from .admissionregistration_v1beta1_service_reference import AdmissionregistrationV1beta1ServiceReferenceDict

AdmissionregistrationV1beta1WebhookClientConfigDict = TypedDict(
    "AdmissionregistrationV1beta1WebhookClientConfigDict",
    {
        "caBundle": str,
        "service": AdmissionregistrationV1beta1ServiceReferenceDict,
        "url": str,
    },
    total=False,
)
