# Code generated by `typeddictgen`. DO NOT EDIT.
"""AdmissionregistrationV1beta1ServiceReferenceDict generated type."""
from typing import TypedDict

AdmissionregistrationV1beta1ServiceReferenceDict = TypedDict(
    "AdmissionregistrationV1beta1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "path": str,
        "port": int,
    },
    total=False,
)
