# Code generated by `typeddictgen`. DO NOT EDIT.
"""AdmissionregistrationV1ServiceReferenceDict generated type."""
from typing import TypedDict

AdmissionregistrationV1ServiceReferenceDict = TypedDict(
    "AdmissionregistrationV1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "path": str,
        "port": int,
    },
    total=False,
)
