# Code generated by `typeddictgen`. DO NOT EDIT.
"""ApiextensionsV1beta1ServiceReferenceDict generated type."""
from typing import TypedDict

ApiextensionsV1beta1ServiceReferenceDict = TypedDict(
    "ApiextensionsV1beta1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "path": str,
        "port": int,
    },
    total=False,
)
