# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

ApiextensionsV1ServiceReferenceDict = TypedDict(
    "ApiextensionsV1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "path": str,
        "port": int,
    },
    total=False,
)
