# Code generated by `typeddictgen`. DO NOT EDIT.
"""ApiregistrationV1ServiceReferenceDict generated type."""
from typing import TypedDict

ApiregistrationV1ServiceReferenceDict = TypedDict(
    "ApiregistrationV1ServiceReferenceDict",
    {
        "name": str,
        "namespace": str,
        "port": int,
    },
    total=False,
)
