# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

AppsV1beta1RollbackConfigDict = TypedDict(
    "AppsV1beta1RollbackConfigDict",
    {
        "revision": int,
    },
    total=False,
)
