# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import AppsV1beta1DeploymentStrategyDict, AppsV1beta1RollbackConfigDict, V1LabelSelectorDict, V1PodTemplateSpecDict

AppsV1beta1DeploymentSpecDict = TypedDict(
    "AppsV1beta1DeploymentSpecDict",
    {
        "minReadySeconds": int,
        "paused": bool,
        "progressDeadlineSeconds": int,
        "replicas": int,
        "revisionHistoryLimit": int,
        "rollbackTo": AppsV1beta1RollbackConfigDict,
        "selector": V1LabelSelectorDict,
        "strategy": AppsV1beta1DeploymentStrategyDict,
        "template": V1PodTemplateSpecDict,
    },
    total=False,
)