# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import AppsV1beta1DeploymentConditionDict

AppsV1beta1DeploymentStatusDict = TypedDict(
    "AppsV1beta1DeploymentStatusDict",
    {
        "availableReplicas": int,
        "collisionCount": int,
        "conditions": List[AppsV1beta1DeploymentConditionDict],
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
        "unavailableReplicas": int,
        "updatedReplicas": int,
    },
    total=False,
)