# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict


AppsV1beta1DeploymentConditionDict = TypedDict(
    "AppsV1beta1DeploymentConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "lastUpdateTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)