# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import AppsV1beta1DeploymentDict, V1ListMetaDict

AppsV1beta1DeploymentListDict = TypedDict(
    "AppsV1beta1DeploymentListDict",
    {
        "apiVersion": str,
        "items": List[AppsV1beta1DeploymentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
