# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import AppsV1beta1DeploymentSpecDict, AppsV1beta1DeploymentStatusDict, V1ObjectMetaDict

AppsV1beta1DeploymentDict = TypedDict(
    "AppsV1beta1DeploymentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": AppsV1beta1DeploymentSpecDict,
        "status": AppsV1beta1DeploymentStatusDict,
    },
    total=False,
)
