# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import AppsV1beta1RollingUpdateDeploymentDict

AppsV1beta1DeploymentStrategyDict = TypedDict(
    "AppsV1beta1DeploymentStrategyDict",
    {
        "rollingUpdate": AppsV1beta1RollingUpdateDeploymentDict,
        "type": str,
    },
    total=False,
)
