# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import (
    ExtensionsV1beta1AllowedCSIDriverDict,
    ExtensionsV1beta1AllowedFlexVolumeDict,
    ExtensionsV1beta1AllowedHostPathDict,
    ExtensionsV1beta1FSGroupStrategyOptionsDict,
    ExtensionsV1beta1HostPortRangeDict,
    ExtensionsV1beta1RunAsGroupStrategyOptionsDict,
    ExtensionsV1beta1RunAsUserStrategyOptionsDict,
    ExtensionsV1beta1RuntimeClassStrategyOptionsDict,
    ExtensionsV1beta1SELinuxStrategyOptionsDict,
    ExtensionsV1beta1SupplementalGroupsStrategyOptionsDict,
)

ExtensionsV1beta1PodSecurityPolicySpecDict = TypedDict(
    "ExtensionsV1beta1PodSecurityPolicySpecDict",
    {
        "allowPrivilegeEscalation": bool,
        "allowedCSIDrivers": List[ExtensionsV1beta1AllowedCSIDriverDict],
        "allowedCapabilities": List[str],
        "allowedFlexVolumes": List[ExtensionsV1beta1AllowedFlexVolumeDict],
        "allowedHostPaths": List[ExtensionsV1beta1AllowedHostPathDict],
        "allowedProcMountTypes": List[str],
        "allowedUnsafeSysctls": List[str],
        "defaultAddCapabilities": List[str],
        "defaultAllowPrivilegeEscalation": bool,
        "forbiddenSysctls": List[str],
        "fsGroup": ExtensionsV1beta1FSGroupStrategyOptionsDict,
        "hostIPC": bool,
        "hostNetwork": bool,
        "hostPID": bool,
        "hostPorts": List[ExtensionsV1beta1HostPortRangeDict],
        "privileged": bool,
        "readOnlyRootFilesystem": bool,
        "requiredDropCapabilities": List[str],
        "runAsGroup": ExtensionsV1beta1RunAsGroupStrategyOptionsDict,
        "runAsUser": ExtensionsV1beta1RunAsUserStrategyOptionsDict,
        "runtimeClass": ExtensionsV1beta1RuntimeClassStrategyOptionsDict,
        "seLinux": ExtensionsV1beta1SELinuxStrategyOptionsDict,
        "supplementalGroups": ExtensionsV1beta1SupplementalGroupsStrategyOptionsDict,
        "volumes": List[str],
    },
    total=False,
)
