# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import ExtensionsV1beta1IngressBackendDict

ExtensionsV1beta1HTTPIngressPathDict = TypedDict(
    "ExtensionsV1beta1HTTPIngressPathDict",
    {
        "backend": ExtensionsV1beta1IngressBackendDict,
        "path": str,
    },
    total=False,
)
