# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import ExtensionsV1beta1PodSecurityPolicyDict, V1ListMetaDict

ExtensionsV1beta1PodSecurityPolicyListDict = TypedDict(
    "ExtensionsV1beta1PodSecurityPolicyListDict",
    {
        "apiVersion": str,
        "items": List[ExtensionsV1beta1PodSecurityPolicyDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)