# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

ExtensionsV1beta1ScaleSpecDict = TypedDict(
    "ExtensionsV1beta1ScaleSpecDict",
    {
        "replicas": int,
    },
    total=False,
)
