# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

ExtensionsV1beta1HostPortRangeDict = TypedDict(
    "ExtensionsV1beta1HostPortRangeDict",
    {
        "max": int,
        "min": int,
    },
    total=False,
)
