# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


ExtensionsV1beta1IDRangeDict = TypedDict(
    "ExtensionsV1beta1IDRangeDict",
    {
        "max": int,
        "min": int,
    },
    total=False,
)