# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import ExtensionsV1beta1ScaleSpecDict, ExtensionsV1beta1ScaleStatusDict, V1ObjectMetaDict

ExtensionsV1beta1ScaleDict = TypedDict(
    "ExtensionsV1beta1ScaleDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": ExtensionsV1beta1ScaleSpecDict,
        "status": ExtensionsV1beta1ScaleStatusDict,
    },
    total=False,
)
