# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

ExtensionsV1beta1AllowedHostPathDict = TypedDict(
    "ExtensionsV1beta1AllowedHostPathDict",
    {
        "pathPrefix": str,
        "readOnly": bool,
    },
    total=False,
)
