# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


ExtensionsV1beta1AllowedFlexVolumeDict = TypedDict(
    "ExtensionsV1beta1AllowedFlexVolumeDict",
    {
        "driver": str,
    },
    total=False,
)