# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

ExtensionsV1beta1RuntimeClassStrategyOptionsDict = TypedDict(
    "ExtensionsV1beta1RuntimeClassStrategyOptionsDict",
    {
        "allowedRuntimeClassNames": List[str],
        "defaultRuntimeClassName": str,
    },
    total=False,
)
