# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import ExtensionsV1beta1IDRangeDict

ExtensionsV1beta1FSGroupStrategyOptionsDict = TypedDict(
    "ExtensionsV1beta1FSGroupStrategyOptionsDict",
    {
        "ranges": List[ExtensionsV1beta1IDRangeDict],
        "rule": str,
    },
    total=False,
)