# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import ExtensionsV1beta1PodSecurityPolicySpecDict, V1ObjectMetaDict

ExtensionsV1beta1PodSecurityPolicyDict = TypedDict(
    "ExtensionsV1beta1PodSecurityPolicyDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": ExtensionsV1beta1PodSecurityPolicySpecDict,
    },
    total=False,
)