# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1IngressRuleDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import NetworkingV1beta1HTTPIngressRuleValueDict

NetworkingV1beta1IngressRuleDict = TypedDict(
    "NetworkingV1beta1IngressRuleDict",
    {
        "host": str,
        "http": NetworkingV1beta1HTTPIngressRuleValueDict,
    },
    total=False,
)
