# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1HTTPIngressPathDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import NetworkingV1beta1IngressBackendDict

NetworkingV1beta1HTTPIngressPathDict = TypedDict(
    "NetworkingV1beta1HTTPIngressPathDict",
    {
        "backend": NetworkingV1beta1IngressBackendDict,
        "path": str,
        "pathType": str,
    },
    total=False,
)
