# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1HTTPIngressRuleValueDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.networking_v1beta1_http_ingress_path import NetworkingV1beta1HTTPIngressPathDict

NetworkingV1beta1HTTPIngressRuleValueDict = TypedDict(
    "NetworkingV1beta1HTTPIngressRuleValueDict",
    {
        "paths": List[NetworkingV1beta1HTTPIngressPathDict],
    },
    total=False,
)
