# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1IngressStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LoadBalancerStatusDict

NetworkingV1beta1IngressStatusDict = TypedDict(
    "NetworkingV1beta1IngressStatusDict",
    {
        "loadBalancer": V1LoadBalancerStatusDict,
    },
    total=False,
)
