# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1IngressDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import NetworkingV1beta1IngressSpecDict, NetworkingV1beta1IngressStatusDict, V1ObjectMetaDict

NetworkingV1beta1IngressDict = TypedDict(
    "NetworkingV1beta1IngressDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": NetworkingV1beta1IngressSpecDict,
        "status": NetworkingV1beta1IngressStatusDict,
    },
    total=False,
)
