# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1IngressTLSDict generated type."""
from typing import TypedDict, List

NetworkingV1beta1IngressTLSDict = TypedDict(
    "NetworkingV1beta1IngressTLSDict",
    {
        "hosts": List[str],
        "secretName": str,
    },
    total=False,
)
