# Code generated by `typeddictgen`. DO NOT EDIT.
"""NetworkingV1beta1IngressDict generated type."""
from typing import TypedDict

from .networking_v1beta1_ingress_spec import NetworkingV1beta1IngressSpecDict
from .networking_v1beta1_ingress_status import NetworkingV1beta1IngressStatusDict
from .v1_object_meta import V1ObjectMetaDict

NetworkingV1beta1IngressDict = TypedDict(
    "NetworkingV1beta1IngressDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": NetworkingV1beta1IngressSpecDict,
        "status": NetworkingV1beta1IngressStatusDict,
    },
    total=False,
)
