# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


NetworkingV1beta1IngressTLSDict = TypedDict(
    "NetworkingV1beta1IngressTLSDict",
    {
        "hosts": List[str],
        "secretName": str,
    },
    total=False,
)