# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import NetworkingV1beta1IngressBackendDict, NetworkingV1beta1IngressRuleDict, NetworkingV1beta1IngressTLSDict

NetworkingV1beta1IngressSpecDict = TypedDict(
    "NetworkingV1beta1IngressSpecDict",
    {
        "backend": NetworkingV1beta1IngressBackendDict,
        "rules": List[NetworkingV1beta1IngressRuleDict],
        "tls": List[NetworkingV1beta1IngressTLSDict],
    },
    total=False,
)