# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


NetworkingV1beta1IngressBackendDict = TypedDict(
    "NetworkingV1beta1IngressBackendDict",
    {
        "serviceName": str,
        "servicePort": object,
    },
    total=False,
)