# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

PolicyV1beta1AllowedCSIDriverDict = TypedDict(
    "PolicyV1beta1AllowedCSIDriverDict",
    {
        "name": str,
    },
    total=False,
)
