# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import PolicyV1beta1PodSecurityPolicySpecDict, V1ObjectMetaDict

PolicyV1beta1PodSecurityPolicyDict = TypedDict(
    "PolicyV1beta1PodSecurityPolicyDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": PolicyV1beta1PodSecurityPolicySpecDict,
    },
    total=False,
)
