# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import PolicyV1beta1IDRangeDict

PolicyV1beta1FSGroupStrategyOptionsDict = TypedDict(
    "PolicyV1beta1FSGroupStrategyOptionsDict",
    {
        "ranges": List[PolicyV1beta1IDRangeDict],
        "rule": str,
    },
    total=False,
)
