# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

PolicyV1beta1IDRangeDict = TypedDict(
    "PolicyV1beta1IDRangeDict",
    {
        "max": int,
        "min": int,
    },
    total=False,
)
