# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import PolicyV1beta1IDRangeDict

PolicyV1beta1RunAsGroupStrategyOptionsDict = TypedDict(
    "PolicyV1beta1RunAsGroupStrategyOptionsDict",
    {
        "ranges": List[PolicyV1beta1IDRangeDict],
        "rule": str,
    },
    total=False,
)