# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

RbacV1alpha1SubjectDict = TypedDict(
    "RbacV1alpha1SubjectDict",
    {
        "apiVersion": str,
        "kind": str,
        "name": str,
        "namespace": str,
    },
    total=False,
)
