# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1AzureDiskVolumeSourceDict = TypedDict(
    "V1AzureDiskVolumeSourceDict",
    {
        "cachingMode": str,
        "diskName": str,
        "diskURI": str,
        "fsType": str,
        "kind": str,
        "readOnly": bool,
    },
    total=False,
)