# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AWSElasticBlockStoreVolumeSourceDict generated type."""
from typing import TypedDict

V1AWSElasticBlockStoreVolumeSourceDict = TypedDict(
    "V1AWSElasticBlockStoreVolumeSourceDict",
    {
        "fsType": str,
        "partition": int,
        "readOnly": bool,
        "volumeID": str,
    },
    total=False,
)
