# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIResourceListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1APIResourceDict

V1APIResourceListDict = TypedDict(
    "V1APIResourceListDict",
    {
        "apiVersion": str,
        "groupVersion": str,
        "kind": str,
        "resources": List[V1APIResourceDict],
    },
    total=False,
)
