# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AffinityDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1NodeAffinityDict, V1PodAffinityDict, V1PodAntiAffinityDict

V1AffinityDict = TypedDict(
    "V1AffinityDict",
    {
        "nodeAffinity": V1NodeAffinityDict,
        "podAffinity": V1PodAffinityDict,
        "podAntiAffinity": V1PodAntiAffinityDict,
    },
    total=False,
)
