# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIServiceListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1APIServiceDict, V1ListMetaDict

V1APIServiceListDict = TypedDict(
    "V1APIServiceListDict",
    {
        "apiVersion": str,
        "items": List[V1APIServiceDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
