# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ServerAddressByClientCIDRDict

V1APIVersionsDict = TypedDict(
    "V1APIVersionsDict",
    {
        "apiVersion": str,
        "kind": str,
        "serverAddressByClientCIDRs": List[V1ServerAddressByClientCIDRDict],
        "versions": List[str],
    },
    total=False,
)
