# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIGroupListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_api_group import V1APIGroupDict

V1APIGroupListDict = TypedDict(
    "V1APIGroupListDict",
    {
        "apiVersion": str,
        "groups": List[V1APIGroupDict],
        "kind": str,
    },
    total=False,
)
