# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1APIVersionsDict generated type."""
from typing import TypedDict, List

from .v1_server_address_by_client_cidr import V1ServerAddressByClientCIDRDict

V1APIVersionsDict = TypedDict(
    "V1APIVersionsDict",
    {
        "apiVersion": str,
        "kind": str,
        "serverAddressByClientCIDRs": List[V1ServerAddressByClientCIDRDict],
        "versions": List[str],
    },
    total=False,
)
