# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1AttachedVolumeDict generated type."""
from typing import TypedDict

V1AttachedVolumeDict = TypedDict(
    "V1AttachedVolumeDict",
    {
        "devicePath": str,
        "name": str,
    },
    total=False,
)
