# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1BindingDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1ObjectReferenceDict

V1BindingDict = TypedDict(
    "V1BindingDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "target": V1ObjectReferenceDict,
    },
    total=False,
)
