# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1BoundObjectReferenceDict = TypedDict(
    "V1BoundObjectReferenceDict",
    {
        "apiVersion": str,
        "kind": str,
        "name": str,
        "uid": str,
    },
    total=False,
)
