# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionStatusDict generated type."""
from typing import TypedDict, List

from .v1_custom_resource_definition_condition import V1CustomResourceDefinitionConditionDict
from .v1_custom_resource_definition_names import V1CustomResourceDefinitionNamesDict

V1CustomResourceDefinitionStatusDict = TypedDict(
    "V1CustomResourceDefinitionStatusDict",
    {
        "acceptedNames": V1CustomResourceDefinitionNamesDict,
        "conditions": List[V1CustomResourceDefinitionConditionDict],
        "storedVersions": List[str],
    },
    total=False,
)
