# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceValidationDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1JSONSchemaPropsDict

V1CustomResourceValidationDict = TypedDict(
    "V1CustomResourceValidationDict",
    {
        "openAPIV3Schema": V1JSONSchemaPropsDict,
    },
    total=False,
)
