# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_csi_driver_spec import V1CSIDriverSpecDict

V1CSIDriverDict = TypedDict(
    "V1CSIDriverDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1CSIDriverSpecDict,
    },
    total=False,
)
