# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


V1CustomResourceDefinitionNamesDict = TypedDict(
    "V1CustomResourceDefinitionNamesDict",
    {
        "categories": List[str],
        "kind": str,
        "listKind": str,
        "plural": str,
        "shortNames": List[str],
        "singular": str,
    },
    total=False,
)