# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ControllerRevisionDict, V1ListMetaDict

V1ControllerRevisionListDict = TypedDict(
    "V1ControllerRevisionListDict",
    {
        "apiVersion": str,
        "items": List[V1ControllerRevisionDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
