# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerImageDict generated type."""
from typing import TypedDict, List

V1ContainerImageDict = TypedDict(
    "V1ContainerImageDict",
    {
        "names": List[str],
        "sizeBytes": int,
    },
    total=False,
)
