# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, Dict


from kubernetes_typed.client import V1ObjectMetaDict

V1ConfigMapDict = TypedDict(
    "V1ConfigMapDict",
    {
        "apiVersion": str,
        "binaryData": Dict[str, str],
        "data": Dict[str, str],
        "kind": str,
        "metadata": V1ObjectMetaDict,
    },
    total=False,
)