# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentConditionDict generated type."""
from typing import TypedDict

V1ComponentConditionDict = TypedDict(
    "V1ComponentConditionDict",
    {
        "error": str,
        "message": str,
        "status": str,
        "type": str,
    },
    total=False,
)
