# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1CSINodeDict, V1ListMetaDict

V1CSINodeListDict = TypedDict(
    "V1CSINodeListDict",
    {
        "apiVersion": str,
        "items": List[V1CSINodeDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
