# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CapabilitiesDict generated type."""
from typing import TypedDict, List

V1CapabilitiesDict = TypedDict(
    "V1CapabilitiesDict",
    {
        "add": List[str],
        "drop": List[str],
    },
    total=False,
)
