# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1ConfigMapEnvSourceDict = TypedDict(
    "V1ConfigMapEnvSourceDict",
    {
        "name": str,
        "optional": bool,
    },
    total=False,
)