# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CephFSPersistentVolumeSourceDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1SecretReferenceDict

V1CephFSPersistentVolumeSourceDict = TypedDict(
    "V1CephFSPersistentVolumeSourceDict",
    {
        "monitors": List[str],
        "path": str,
        "readOnly": bool,
        "secretFile": str,
        "secretRef": V1SecretReferenceDict,
        "user": str,
    },
    total=False,
)
