# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ComponentStatusDict, V1ListMetaDict

V1ComponentStatusListDict = TypedDict(
    "V1ComponentStatusListDict",
    {
        "apiVersion": str,
        "items": List[V1ComponentStatusDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
