# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1CSIDriverDict, V1ListMetaDict

V1CSIDriverListDict = TypedDict(
    "V1CSIDriverListDict",
    {
        "apiVersion": str,
        "items": List[V1CSIDriverDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
