# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ClusterRoleBindingListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ClusterRoleBindingDict, V1ListMetaDict

V1ClusterRoleBindingListDict = TypedDict(
    "V1ClusterRoleBindingListDict",
    {
        "apiVersion": str,
        "items": List[V1ClusterRoleBindingDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
