# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1KeyToPathDict

V1ConfigMapProjectionDict = TypedDict(
    "V1ConfigMapProjectionDict",
    {
        "items": List[V1KeyToPathDict],
        "name": str,
        "optional": bool,
    },
    total=False,
)