# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeDict generated type."""
from typing import TypedDict

from .v1_csi_node_spec import V1CSINodeSpecDict
from .v1_object_meta import V1ObjectMetaDict

V1CSINodeDict = TypedDict(
    "V1CSINodeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1CSINodeSpecDict,
    },
    total=False,
)
