# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStateRunningDict generated type."""
import datetime
from typing import TypedDict

V1ContainerStateRunningDict = TypedDict(
    "V1ContainerStateRunningDict",
    {
        "startedAt": datetime.datetime,
    },
    total=False,
)
