# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapListDict generated type."""
from typing import TypedDict, List

from .v1_config_map import V1ConfigMapDict
from .v1_list_meta import V1ListMetaDict

V1ConfigMapListDict = TypedDict(
    "V1ConfigMapListDict",
    {
        "apiVersion": str,
        "items": List[V1ConfigMapDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
