# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1CrossVersionObjectReferenceDict = TypedDict(
    "V1CrossVersionObjectReferenceDict",
    {
        "apiVersion": str,
        "kind": str,
        "name": str,
    },
    total=False,
)
