# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeListDict generated type."""
from typing import TypedDict, List

from .v1_csi_node import V1CSINodeDict
from .v1_list_meta import V1ListMetaDict

V1CSINodeListDict = TypedDict(
    "V1CSINodeListDict",
    {
        "apiVersion": str,
        "items": List[V1CSINodeDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
