# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIDriverDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1CSIDriverSpecDict, V1ObjectMetaDict

V1CSIDriverDict = TypedDict(
    "V1CSIDriverDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1CSIDriverSpecDict,
    },
    total=False,
)
