# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1ConfigMapKeySelectorDict = TypedDict(
    "V1ConfigMapKeySelectorDict",
    {
        "key": str,
        "name": str,
        "optional": bool,
    },
    total=False,
)
