# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceDefinitionDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_custom_resource_definition_spec import V1CustomResourceDefinitionSpecDict
from kubernetes_typed.client.models.v1_custom_resource_definition_status import V1CustomResourceDefinitionStatusDict

V1CustomResourceDefinitionDict = TypedDict(
    "V1CustomResourceDefinitionDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1CustomResourceDefinitionSpecDict,
        "status": V1CustomResourceDefinitionStatusDict,
    },
    total=False,
)
