# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSIPersistentVolumeSourceDict generated type."""
from typing import TypedDict, Dict

from kubernetes_typed.client import V1SecretReferenceDict

V1CSIPersistentVolumeSourceDict = TypedDict(
    "V1CSIPersistentVolumeSourceDict",
    {
        "controllerExpandSecretRef": V1SecretReferenceDict,
        "controllerPublishSecretRef": V1SecretReferenceDict,
        "driver": str,
        "fsType": str,
        "nodePublishSecretRef": V1SecretReferenceDict,
        "nodeStageSecretRef": V1SecretReferenceDict,
        "readOnly": bool,
        "volumeAttributes": Dict[str, str],
        "volumeHandle": str,
    },
    total=False,
)
