# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict


V1ContainerStateRunningDict = TypedDict(
    "V1ContainerStateRunningDict",
    {
        "startedAt": datetime.datetime,
    },
    total=False,
)