# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerStateDict generated type."""
from typing import TypedDict

from .v1_container_state_running import V1ContainerStateRunningDict
from .v1_container_state_terminated import V1ContainerStateTerminatedDict
from .v1_container_state_waiting import V1ContainerStateWaitingDict

V1ContainerStateDict = TypedDict(
    "V1ContainerStateDict",
    {
        "running": V1ContainerStateRunningDict,
        "terminated": V1ContainerStateTerminatedDict,
        "waiting": V1ContainerStateWaitingDict,
    },
    total=False,
)
