# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapProjectionDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_key_to_path import V1KeyToPathDict

V1ConfigMapProjectionDict = TypedDict(
    "V1ConfigMapProjectionDict",
    {
        "items": List[V1KeyToPathDict],
        "name": str,
        "optional": bool,
    },
    total=False,
)
