# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ConfigMapEnvSourceDict generated type."""
from typing import TypedDict

V1ConfigMapEnvSourceDict = TypedDict(
    "V1ConfigMapEnvSourceDict",
    {
        "name": str,
        "optional": bool,
    },
    total=False,
)
