# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CustomResourceColumnDefinitionDict generated type."""
from typing import TypedDict

V1CustomResourceColumnDefinitionDict = TypedDict(
    "V1CustomResourceColumnDefinitionDict",
    {
        "description": str,
        "format": str,
        "jsonPath": str,
        "name": str,
        "priority": int,
        "type": str,
    },
    total=False,
)
