# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1CSINodeDriverDict

V1CSINodeSpecDict = TypedDict(
    "V1CSINodeSpecDict",
    {
        "drivers": List[V1CSINodeDriverDict],
    },
    total=False,
)
