# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ComponentConditionDict, V1ObjectMetaDict

V1ComponentStatusDict = TypedDict(
    "V1ComponentStatusDict",
    {
        "apiVersion": str,
        "conditions": List[V1ComponentConditionDict],
        "kind": str,
        "metadata": V1ObjectMetaDict,
    },
    total=False,
)
