# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1CustomResourceSubresourceScaleDict = TypedDict(
    "V1CustomResourceSubresourceScaleDict",
    {
        "labelSelectorPath": str,
        "specReplicasPath": str,
        "statusReplicasPath": str,
    },
    total=False,
)