# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ComponentStatusDict generated type."""
from typing import TypedDict, List

from .v1_component_condition import V1ComponentConditionDict
from .v1_object_meta import V1ObjectMetaDict

V1ComponentStatusDict = TypedDict(
    "V1ComponentStatusDict",
    {
        "apiVersion": str,
        "conditions": List[V1ComponentConditionDict],
        "kind": str,
        "metadata": V1ObjectMetaDict,
    },
    total=False,
)
