# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1CSINodeDriverDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1VolumeNodeResourcesDict

V1CSINodeDriverDict = TypedDict(
    "V1CSINodeDriverDict",
    {
        "allocatable": V1VolumeNodeResourcesDict,
        "name": str,
        "nodeID": str,
        "topologyKeys": List[str],
    },
    total=False,
)
