# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ContainerDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_env_var import V1EnvVarDict
from kubernetes_typed.client.models.v1_env_from_source import V1EnvFromSourceDict
from kubernetes_typed.client.models.v1_lifecycle import V1LifecycleDict
from kubernetes_typed.client.models.v1_probe import V1ProbeDict
from kubernetes_typed.client.models.v1_container_port import V1ContainerPortDict
from kubernetes_typed.client.models.v1_resource_requirements import V1ResourceRequirementsDict
from kubernetes_typed.client.models.v1_security_context import V1SecurityContextDict
from kubernetes_typed.client.models.v1_volume_device import V1VolumeDeviceDict
from kubernetes_typed.client.models.v1_volume_mount import V1VolumeMountDict

V1ContainerDict = TypedDict(
    "V1ContainerDict",
    {
        "args": List[str],
        "command": List[str],
        "env": List[V1EnvVarDict],
        "envFrom": List[V1EnvFromSourceDict],
        "image": str,
        "imagePullPolicy": str,
        "lifecycle": V1LifecycleDict,
        "livenessProbe": V1ProbeDict,
        "name": str,
        "ports": List[V1ContainerPortDict],
        "readinessProbe": V1ProbeDict,
        "resources": V1ResourceRequirementsDict,
        "securityContext": V1SecurityContextDict,
        "startupProbe": V1ProbeDict,
        "stdin": bool,
        "stdinOnce": bool,
        "terminationMessagePath": str,
        "terminationMessagePolicy": str,
        "tty": bool,
        "volumeDevices": List[V1VolumeDeviceDict],
        "volumeMounts": List[V1VolumeMountDict],
        "workingDir": str,
    },
    total=False,
)
