# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonEndpointDict generated type."""
from typing import TypedDict

V1DaemonEndpointDict = TypedDict(
    "V1DaemonEndpointDict",
    {
        "Port": int,
    },
    total=False,
)
