# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DeploymentListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_deployment import V1DeploymentDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1DeploymentListDict = TypedDict(
    "V1DeploymentListDict",
    {
        "apiVersion": str,
        "items": List[V1DeploymentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
