# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DownwardAPIProjectionDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1DownwardAPIVolumeFileDict

V1DownwardAPIProjectionDict = TypedDict(
    "V1DownwardAPIProjectionDict",
    {
        "items": List[V1DownwardAPIVolumeFileDict],
    },
    total=False,
)
