# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1DaemonSetDict, V1ListMetaDict

V1DaemonSetListDict = TypedDict(
    "V1DaemonSetListDict",
    {
        "apiVersion": str,
        "items": List[V1DaemonSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
