# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorDict
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecDict
from kubernetes_typed.client.models.v1_daemon_set_update_strategy import V1DaemonSetUpdateStrategyDict

V1DaemonSetSpecDict = TypedDict(
    "V1DaemonSetSpecDict",
    {
        "minReadySeconds": int,
        "revisionHistoryLimit": int,
        "selector": V1LabelSelectorDict,
        "template": V1PodTemplateSpecDict,
        "updateStrategy": V1DaemonSetUpdateStrategyDict,
    },
    total=False,
)
