# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1DaemonSetDict generated type."""
from typing import TypedDict

from .v1_daemon_set_spec import V1DaemonSetSpecDict
from .v1_daemon_set_status import V1DaemonSetStatusDict
from .v1_object_meta import V1ObjectMetaDict

V1DaemonSetDict = TypedDict(
    "V1DaemonSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1DaemonSetSpecDict,
        "status": V1DaemonSetStatusDict,
    },
    total=False,
)
