# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvVarSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ConfigMapKeySelectorDict, V1ObjectFieldSelectorDict, V1ResourceFieldSelectorDict, V1SecretKeySelectorDict

V1EnvVarSourceDict = TypedDict(
    "V1EnvVarSourceDict",
    {
        "configMapKeyRef": V1ConfigMapKeySelectorDict,
        "fieldRef": V1ObjectFieldSelectorDict,
        "resourceFieldRef": V1ResourceFieldSelectorDict,
        "secretKeyRef": V1SecretKeySelectorDict,
    },
    total=False,
)
