# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EmptyDirVolumeSourceDict generated type."""
from typing import TypedDict

V1EmptyDirVolumeSourceDict = TypedDict(
    "V1EmptyDirVolumeSourceDict",
    {
        "medium": str,
        "sizeLimit": str,
    },
    total=False,
)
