# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EventDict generated type."""
import datetime
from typing import TypedDict

from kubernetes_typed.client import V1EventSeriesDict, V1EventSourceDict, V1ObjectMetaDict, V1ObjectReferenceDict

V1EventDict = TypedDict(
    "V1EventDict",
    {
        "action": str,
        "apiVersion": str,
        "count": int,
        "eventTime": datetime.datetime,
        "firstTimestamp": datetime.datetime,
        "involvedObject": V1ObjectReferenceDict,
        "kind": str,
        "lastTimestamp": datetime.datetime,
        "message": str,
        "metadata": V1ObjectMetaDict,
        "reason": str,
        "related": V1ObjectReferenceDict,
        "reportingComponent": str,
        "reportingInstance": str,
        "series": V1EventSeriesDict,
        "source": V1EventSourceDict,
        "type": str,
    },
    total=False,
)
