# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvVarDict generated type."""
from typing import TypedDict

from .v1_env_var_source import V1EnvVarSourceDict

V1EnvVarDict = TypedDict(
    "V1EnvVarDict",
    {
        "name": str,
        "value": str,
        "valueFrom": V1EnvVarSourceDict,
    },
    total=False,
)
