# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1EndpointPortDict = TypedDict(
    "V1EndpointPortDict",
    {
        "name": str,
        "port": int,
        "protocol": str,
    },
    total=False,
)
