# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EventDict generated type."""
import datetime
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_reference import V1ObjectReferenceDict
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_event_series import V1EventSeriesDict
from kubernetes_typed.client.models.v1_event_source import V1EventSourceDict

V1EventDict = TypedDict(
    "V1EventDict",
    {
        "action": str,
        "apiVersion": str,
        "count": int,
        "eventTime": datetime.datetime,
        "firstTimestamp": datetime.datetime,
        "involvedObject": V1ObjectReferenceDict,
        "kind": str,
        "lastTimestamp": datetime.datetime,
        "message": str,
        "metadata": V1ObjectMetaDict,
        "reason": str,
        "related": V1ObjectReferenceDict,
        "reportingComponent": str,
        "reportingInstance": str,
        "series": V1EventSeriesDict,
        "source": V1EventSourceDict,
        "type": str,
    },
    total=False,
)
