# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EndpointsListDict generated type."""
from typing import TypedDict, List

from .v1_endpoints import V1EndpointsDict
from .v1_list_meta import V1ListMetaDict

V1EndpointsListDict = TypedDict(
    "V1EndpointsListDict",
    {
        "apiVersion": str,
        "items": List[V1EndpointsDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
