# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ExecActionDict generated type."""
from typing import TypedDict, List

V1ExecActionDict = TypedDict(
    "V1ExecActionDict",
    {
        "command": List[str],
    },
    total=False,
)
