# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvFromSourceDict generated type."""
from typing import TypedDict

from .v1_config_map_env_source import V1ConfigMapEnvSourceDict
from .v1_secret_env_source import V1SecretEnvSourceDict

V1EnvFromSourceDict = TypedDict(
    "V1EnvFromSourceDict",
    {
        "configMapRef": V1ConfigMapEnvSourceDict,
        "prefix": str,
        "secretRef": V1SecretEnvSourceDict,
    },
    total=False,
)
