# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1EventDict, V1ListMetaDict

V1EventListDict = TypedDict(
    "V1EventListDict",
    {
        "apiVersion": str,
        "items": List[V1EventDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
