# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1ExternalDocumentationDict = TypedDict(
    "V1ExternalDocumentationDict",
    {
        "description": str,
        "url": str,
    },
    total=False,
)