# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1EnvFromSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ConfigMapEnvSourceDict, V1SecretEnvSourceDict

V1EnvFromSourceDict = TypedDict(
    "V1EnvFromSourceDict",
    {
        "configMapRef": V1ConfigMapEnvSourceDict,
        "prefix": str,
        "secretRef": V1SecretEnvSourceDict,
    },
    total=False,
)
