# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, Dict


from kubernetes_typed.client import V1SecretReferenceDict

V1FlexPersistentVolumeSourceDict = TypedDict(
    "V1FlexPersistentVolumeSourceDict",
    {
        "driver": str,
        "fsType": str,
        "options": Dict[str, str],
        "readOnly": bool,
        "secretRef": V1SecretReferenceDict,
    },
    total=False,
)