# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1GroupVersionForDiscoveryDict = TypedDict(
    "V1GroupVersionForDiscoveryDict",
    {
        "groupVersion": str,
        "version": str,
    },
    total=False,
)