# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GlusterfsVolumeSourceDict generated type."""
from typing import TypedDict

V1GlusterfsVolumeSourceDict = TypedDict(
    "V1GlusterfsVolumeSourceDict",
    {
        "endpoints": str,
        "path": str,
        "readOnly": bool,
    },
    total=False,
)
