# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1GlusterfsPersistentVolumeSourceDict generated type."""
from typing import TypedDict

V1GlusterfsPersistentVolumeSourceDict = TypedDict(
    "V1GlusterfsPersistentVolumeSourceDict",
    {
        "endpoints": str,
        "endpointsNamespace": str,
        "path": str,
        "readOnly": bool,
    },
    total=False,
)
