# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1GitRepoVolumeSourceDict = TypedDict(
    "V1GitRepoVolumeSourceDict",
    {
        "directory": str,
        "repository": str,
        "revision": str,
    },
    total=False,
)
