# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerListDict generated type."""
from typing import TypedDict, List

from .v1_horizontal_pod_autoscaler import V1HorizontalPodAutoscalerDict
from .v1_list_meta import V1ListMetaDict

V1HorizontalPodAutoscalerListDict = TypedDict(
    "V1HorizontalPodAutoscalerListDict",
    {
        "apiVersion": str,
        "items": List[V1HorizontalPodAutoscalerDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
