# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HorizontalPodAutoscalerStatusDict generated type."""
import datetime
from typing import TypedDict

V1HorizontalPodAutoscalerStatusDict = TypedDict(
    "V1HorizontalPodAutoscalerStatusDict",
    {
        "currentCPUUtilizationPercentage": int,
        "currentReplicas": int,
        "desiredReplicas": int,
        "lastScaleTime": datetime.datetime,
        "observedGeneration": int,
    },
    total=False,
)
