# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


V1HostAliasDict = TypedDict(
    "V1HostAliasDict",
    {
        "hostnames": List[str],
        "ip": str,
    },
    total=False,
)