# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HostAliasDict generated type."""
from typing import TypedDict, List

V1HostAliasDict = TypedDict(
    "V1HostAliasDict",
    {
        "hostnames": List[str],
        "ip": str,
    },
    total=False,
)
