# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPHeaderDict generated type."""
from typing import TypedDict

V1HTTPHeaderDict = TypedDict(
    "V1HTTPHeaderDict",
    {
        "name": str,
        "value": str,
    },
    total=False,
)
