# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HTTPGetActionDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_http_header import V1HTTPHeaderDict

V1HTTPGetActionDict = TypedDict(
    "V1HTTPGetActionDict",
    {
        "host": str,
        "httpHeaders": List[V1HTTPHeaderDict],
        "path": str,
        "port": object,
        "scheme": str,
    },
    total=False,
)
