# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1HandlerDict generated type."""
from typing import TypedDict

from .v1_exec_action import V1ExecActionDict
from .v1_http_get_action import V1HTTPGetActionDict
from .v1_tcp_socket_action import V1TCPSocketActionDict

V1HandlerDict = TypedDict(
    "V1HandlerDict",
    {
        "exec": V1ExecActionDict,
        "httpGet": V1HTTPGetActionDict,
        "tcpSocket": V1TCPSocketActionDict,
    },
    total=False,
)
