# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ISCSIVolumeSourceDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1LocalObjectReferenceDict

V1ISCSIVolumeSourceDict = TypedDict(
    "V1ISCSIVolumeSourceDict",
    {
        "chapAuthDiscovery": bool,
        "chapAuthSession": bool,
        "fsType": str,
        "initiatorName": str,
        "iqn": str,
        "iscsiInterface": str,
        "lun": int,
        "portals": List[str],
        "readOnly": bool,
        "secretRef": V1LocalObjectReferenceDict,
        "targetPortal": str,
    },
    total=False,
)
