# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1KeyToPathDict = TypedDict(
    "V1KeyToPathDict",
    {
        "key": str,
        "mode": int,
        "path": str,
    },
    total=False,
)