# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1KeyToPathDict generated type."""
from typing import TypedDict

V1KeyToPathDict = TypedDict(
    "V1KeyToPathDict",
    {
        "key": str,
        "mode": int,
        "path": str,
    },
    total=False,
)
