# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LocalObjectReferenceDict generated type."""
from typing import TypedDict

V1LocalObjectReferenceDict = TypedDict(
    "V1LocalObjectReferenceDict",
    {
        "name": str,
    },
    total=False,
)
