# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeSpecDict generated type."""
from typing import TypedDict, List

from .v1_limit_range_item import V1LimitRangeItemDict

V1LimitRangeSpecDict = TypedDict(
    "V1LimitRangeSpecDict",
    {
        "limits": List[V1LimitRangeItemDict],
    },
    total=False,
)
