# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LimitRangeSpecDict, V1ObjectMetaDict

V1LimitRangeDict = TypedDict(
    "V1LimitRangeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1LimitRangeSpecDict,
    },
    total=False,
)
