# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1ListMetaDict = TypedDict(
    "V1ListMetaDict",
    {
        "continue": str,
        "remainingItemCount": int,
        "resourceVersion": str,
        "selfLink": str,
    },
    total=False,
)