# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LocalSubjectAccessReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1SubjectAccessReviewSpecDict, V1SubjectAccessReviewStatusDict

V1LocalSubjectAccessReviewDict = TypedDict(
    "V1LocalSubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1SubjectAccessReviewSpecDict,
        "status": V1SubjectAccessReviewStatusDict,
    },
    total=False,
)
