# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LocalSubjectAccessReviewDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1_subject_access_review_spec import V1SubjectAccessReviewSpecDict
from .v1_subject_access_review_status import V1SubjectAccessReviewStatusDict

V1LocalSubjectAccessReviewDict = TypedDict(
    "V1LocalSubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1SubjectAccessReviewSpecDict,
        "status": V1SubjectAccessReviewStatusDict,
    },
    total=False,
)
