# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, Dict


V1LimitRangeItemDict = TypedDict(
    "V1LimitRangeItemDict",
    {
        "default": Dict[str, str],
        "defaultRequest": Dict[str, str],
        "max": Dict[str, str],
        "maxLimitRequestRatio": Dict[str, str],
        "min": Dict[str, str],
        "type": str,
    },
    total=False,
)