# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LocalVolumeSourceDict generated type."""
from typing import TypedDict

V1LocalVolumeSourceDict = TypedDict(
    "V1LocalVolumeSourceDict",
    {
        "fsType": str,
        "path": str,
    },
    total=False,
)
