# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1LocalVolumeSourceDict = TypedDict(
    "V1LocalVolumeSourceDict",
    {
        "fsType": str,
        "path": str,
    },
    total=False,
)