# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LabelSelectorRequirementDict generated type."""
from typing import TypedDict, List

V1LabelSelectorRequirementDict = TypedDict(
    "V1LabelSelectorRequirementDict",
    {
        "key": str,
        "operator": str,
        "values": List[str],
    },
    total=False,
)
