# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LoadBalancerIngressDict generated type."""
from typing import TypedDict

V1LoadBalancerIngressDict = TypedDict(
    "V1LoadBalancerIngressDict",
    {
        "hostname": str,
        "ip": str,
    },
    total=False,
)
