# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1LocalObjectReferenceDict = TypedDict(
    "V1LocalObjectReferenceDict",
    {
        "name": str,
    },
    total=False,
)