# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1LimitRangeListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_limit_range import V1LimitRangeDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1LimitRangeListDict = TypedDict(
    "V1LimitRangeListDict",
    {
        "apiVersion": str,
        "items": List[V1LimitRangeDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
