# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1MutatingWebhookConfigurationDict

V1MutatingWebhookConfigurationListDict = TypedDict(
    "V1MutatingWebhookConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1MutatingWebhookConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
