# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict

V1ManagedFieldsEntryDict = TypedDict(
    "V1ManagedFieldsEntryDict",
    {
        "apiVersion": str,
        "fieldsType": str,
        "fieldsV1": object,
        "manager": str,
        "operation": str,
        "time": datetime.datetime,
    },
    total=False,
)
