# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeStatusDict generated type."""
from typing import TypedDict, Dict, List

from .v1_attached_volume import V1AttachedVolumeDict
from .v1_container_image import V1ContainerImageDict
from .v1_node_address import V1NodeAddressDict
from .v1_node_condition import V1NodeConditionDict
from .v1_node_config_status import V1NodeConfigStatusDict
from .v1_node_daemon_endpoints import V1NodeDaemonEndpointsDict
from .v1_node_system_info import V1NodeSystemInfoDict

V1NodeStatusDict = TypedDict(
    "V1NodeStatusDict",
    {
        "addresses": List[V1NodeAddressDict],
        "allocatable": Dict[str, str],
        "capacity": Dict[str, str],
        "conditions": List[V1NodeConditionDict],
        "config": V1NodeConfigStatusDict,
        "daemonEndpoints": V1NodeDaemonEndpointsDict,
        "images": List[V1ContainerImageDict],
        "nodeInfo": V1NodeSystemInfoDict,
        "phase": str,
        "volumesAttached": List[V1AttachedVolumeDict],
        "volumesInUse": List[str],
    },
    total=False,
)
