# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ConfigMapNodeConfigSourceDict

V1NodeConfigSourceDict = TypedDict(
    "V1NodeConfigSourceDict",
    {
        "configMap": V1ConfigMapNodeConfigSourceDict,
    },
    total=False,
)
