# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1NodeConfigSourceDict, V1TaintDict

V1NodeSpecDict = TypedDict(
    "V1NodeSpecDict",
    {
        "configSource": V1NodeConfigSourceDict,
        "externalID": str,
        "podCIDR": str,
        "podCIDRs": List[str],
        "providerID": str,
        "taints": List[V1TaintDict],
        "unschedulable": bool,
    },
    total=False,
)
