# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeAddressDict generated type."""
from typing import TypedDict

V1NodeAddressDict = TypedDict(
    "V1NodeAddressDict",
    {
        "address": str,
        "type": str,
    },
    total=False,
)
