# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicySpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_network_policy_egress_rule import V1NetworkPolicyEgressRuleDict
from kubernetes_typed.client.models.v1_network_policy_ingress_rule import V1NetworkPolicyIngressRuleDict
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorDict

V1NetworkPolicySpecDict = TypedDict(
    "V1NetworkPolicySpecDict",
    {
        "egress": List[V1NetworkPolicyEgressRuleDict],
        "ingress": List[V1NetworkPolicyIngressRuleDict],
        "podSelector": V1LabelSelectorDict,
        "policyTypes": List[str],
    },
    total=False,
)
