# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeConfigSourceDict generated type."""
from typing import TypedDict

from .v1_config_map_node_config_source import V1ConfigMapNodeConfigSourceDict

V1NodeConfigSourceDict = TypedDict(
    "V1NodeConfigSourceDict",
    {
        "configMap": V1ConfigMapNodeConfigSourceDict,
    },
    total=False,
)
