# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorDict generated type."""
from typing import TypedDict, List

from .v1_node_selector_term import V1NodeSelectorTermDict

V1NodeSelectorDict = TypedDict(
    "V1NodeSelectorDict",
    {
        "nodeSelectorTerms": List[V1NodeSelectorTermDict],
    },
    total=False,
)
