# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyEgressRuleDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1NetworkPolicyPeerDict, V1NetworkPolicyPortDict

V1NetworkPolicyEgressRuleDict = TypedDict(
    "V1NetworkPolicyEgressRuleDict",
    {
        "ports": List[V1NetworkPolicyPortDict],
        "to": List[V1NetworkPolicyPeerDict],
    },
    total=False,
)
