# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict

V1NodeConditionDict = TypedDict(
    "V1NodeConditionDict",
    {
        "lastHeartbeatTime": datetime.datetime,
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
