# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1NamespaceConditionDict

V1NamespaceStatusDict = TypedDict(
    "V1NamespaceStatusDict",
    {
        "conditions": List[V1NamespaceConditionDict],
        "phase": str,
    },
    total=False,
)
