# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_namespace_spec import V1NamespaceSpecDict
from kubernetes_typed.client.models.v1_namespace_status import V1NamespaceStatusDict

V1NamespaceDict = TypedDict(
    "V1NamespaceDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1NamespaceSpecDict,
        "status": V1NamespaceStatusDict,
    },
    total=False,
)
