# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyPeerDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1IPBlockDict, V1LabelSelectorDict

V1NetworkPolicyPeerDict = TypedDict(
    "V1NetworkPolicyPeerDict",
    {
        "ipBlock": V1IPBlockDict,
        "namespaceSelector": V1LabelSelectorDict,
        "podSelector": V1LabelSelectorDict,
    },
    total=False,
)
