# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

V1NonResourceRuleDict = TypedDict(
    "V1NonResourceRuleDict",
    {
        "nonResourceURLs": List[str],
        "verbs": List[str],
    },
    total=False,
)
