# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeDict generated type."""
from typing import TypedDict

from .v1_node_spec import V1NodeSpecDict
from .v1_node_status import V1NodeStatusDict
from .v1_object_meta import V1ObjectMetaDict

V1NodeDict = TypedDict(
    "V1NodeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1NodeSpecDict,
        "status": V1NodeStatusDict,
    },
    total=False,
)
