# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeConfigStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1NodeConfigSourceDict

V1NodeConfigStatusDict = TypedDict(
    "V1NodeConfigStatusDict",
    {
        "active": V1NodeConfigSourceDict,
        "assigned": V1NodeConfigSourceDict,
        "error": str,
        "lastKnownGood": V1NodeConfigSourceDict,
    },
    total=False,
)
