# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeSelectorRequirementDict generated type."""
from typing import TypedDict, List

V1NodeSelectorRequirementDict = TypedDict(
    "V1NodeSelectorRequirementDict",
    {
        "key": str,
        "operator": str,
        "values": List[str],
    },
    total=False,
)
