# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1NamespaceSpecDict, V1NamespaceStatusDict, V1ObjectMetaDict

V1NamespaceDict = TypedDict(
    "V1NamespaceDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1NamespaceSpecDict,
        "status": V1NamespaceStatusDict,
    },
    total=False,
)
