# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

V1NamespaceSpecDict = TypedDict(
    "V1NamespaceSpecDict",
    {
        "finalizers": List[str],
    },
    total=False,
)
