# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1NFSVolumeSourceDict = TypedDict(
    "V1NFSVolumeSourceDict",
    {
        "path": str,
        "readOnly": bool,
        "server": str,
    },
    total=False,
)