# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NetworkPolicyListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1_network_policy import V1NetworkPolicyDict

V1NetworkPolicyListDict = TypedDict(
    "V1NetworkPolicyListDict",
    {
        "apiVersion": str,
        "items": List[V1NetworkPolicyDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
