# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NodeListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_node import V1NodeDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1NodeListDict = TypedDict(
    "V1NodeListDict",
    {
        "apiVersion": str,
        "items": List[V1NodeDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
