# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1NamespaceListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1_namespace import V1NamespaceDict

V1NamespaceListDict = TypedDict(
    "V1NamespaceListDict",
    {
        "apiVersion": str,
        "items": List[V1NamespaceDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
