# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ObjectFieldSelectorDict generated type."""
from typing import TypedDict

V1ObjectFieldSelectorDict = TypedDict(
    "V1ObjectFieldSelectorDict",
    {
        "apiVersion": str,
        "fieldPath": str,
    },
    total=False,
)
