# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_persistent_volume_claim_spec import V1PersistentVolumeClaimSpecDict
from kubernetes_typed.client.models.v1_persistent_volume_claim_status import V1PersistentVolumeClaimStatusDict

V1PersistentVolumeClaimDict = TypedDict(
    "V1PersistentVolumeClaimDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1PersistentVolumeClaimSpecDict,
        "status": V1PersistentVolumeClaimStatusDict,
    },
    total=False,
)
