# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1PodTemplateSpecDict

V1PodTemplateDict = TypedDict(
    "V1PodTemplateDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "template": V1PodTemplateSpecDict,
    },
    total=False,
)
