# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeStatusDict generated type."""
from typing import TypedDict

V1PersistentVolumeStatusDict = TypedDict(
    "V1PersistentVolumeStatusDict",
    {
        "message": str,
        "phase": str,
        "reason": str,
    },
    total=False,
)
