# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1PodDNSConfigOptionDict = TypedDict(
    "V1PodDNSConfigOptionDict",
    {
        "name": str,
        "value": str,
    },
    total=False,
)
