# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1PodTemplateDict

V1PodTemplateListDict = TypedDict(
    "V1PodTemplateListDict",
    {
        "apiVersion": str,
        "items": List[V1PodTemplateDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
