# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PhotonPersistentDiskVolumeSourceDict generated type."""
from typing import TypedDict

V1PhotonPersistentDiskVolumeSourceDict = TypedDict(
    "V1PhotonPersistentDiskVolumeSourceDict",
    {
        "fsType": str,
        "pdID": str,
    },
    total=False,
)
