# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodSecurityContextDict generated type."""
from typing import TypedDict, List

from .v1_se_linux_options import V1SELinuxOptionsDict
from .v1_sysctl import V1SysctlDict
from .v1_windows_security_context_options import V1WindowsSecurityContextOptionsDict

V1PodSecurityContextDict = TypedDict(
    "V1PodSecurityContextDict",
    {
        "fsGroup": int,
        "fsGroupChangePolicy": str,
        "runAsGroup": int,
        "runAsNonRoot": bool,
        "runAsUser": int,
        "seLinuxOptions": V1SELinuxOptionsDict,
        "supplementalGroups": List[int],
        "sysctls": List[V1SysctlDict],
        "windowsOptions": V1WindowsSecurityContextOptionsDict,
    },
    total=False,
)
