# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1PodDNSConfigOptionDict

V1PodDNSConfigDict = TypedDict(
    "V1PodDNSConfigDict",
    {
        "nameservers": List[str],
        "options": List[V1PodDNSConfigOptionDict],
        "searches": List[str],
    },
    total=False,
)
