# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1PodReadinessGateDict = TypedDict(
    "V1PodReadinessGateDict",
    {
        "conditionType": str,
    },
    total=False,
)