# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1PreconditionsDict = TypedDict(
    "V1PreconditionsDict",
    {
        "resourceVersion": str,
        "uid": str,
    },
    total=False,
)