# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimVolumeSourceDict generated type."""
from typing import TypedDict

V1PersistentVolumeClaimVolumeSourceDict = TypedDict(
    "V1PersistentVolumeClaimVolumeSourceDict",
    {
        "claimName": str,
        "readOnly": bool,
    },
    total=False,
)
