# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1PersistentVolumeSpecDict, V1PersistentVolumeStatusDict

V1PersistentVolumeDict = TypedDict(
    "V1PersistentVolumeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1PersistentVolumeSpecDict,
        "status": V1PersistentVolumeStatusDict,
    },
    total=False,
)
