# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodAntiAffinityDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_weighted_pod_affinity_term import V1WeightedPodAffinityTermDict
from kubernetes_typed.client.models.v1_pod_affinity_term import V1PodAffinityTermDict

V1PodAntiAffinityDict = TypedDict(
    "V1PodAntiAffinityDict",
    {
        "preferredDuringSchedulingIgnoredDuringExecution": List[V1WeightedPodAffinityTermDict],
        "requiredDuringSchedulingIgnoredDuringExecution": List[V1PodAffinityTermDict],
    },
    total=False,
)
