# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1PersistentVolumeClaimDict

V1PersistentVolumeClaimListDict = TypedDict(
    "V1PersistentVolumeClaimListDict",
    {
        "apiVersion": str,
        "items": List[V1PersistentVolumeClaimDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
