# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeSpecDict generated type."""
from typing import TypedDict, Dict, List

from .v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSourceDict
from .v1_azure_disk_volume_source import V1AzureDiskVolumeSourceDict
from .v1_azure_file_persistent_volume_source import V1AzureFilePersistentVolumeSourceDict
from .v1_csi_persistent_volume_source import V1CSIPersistentVolumeSourceDict
from .v1_ceph_fs_persistent_volume_source import V1CephFSPersistentVolumeSourceDict
from .v1_cinder_persistent_volume_source import V1CinderPersistentVolumeSourceDict
from .v1_fc_volume_source import V1FCVolumeSourceDict
from .v1_flex_persistent_volume_source import V1FlexPersistentVolumeSourceDict
from .v1_flocker_volume_source import V1FlockerVolumeSourceDict
from .v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSourceDict
from .v1_glusterfs_persistent_volume_source import V1GlusterfsPersistentVolumeSourceDict
from .v1_host_path_volume_source import V1HostPathVolumeSourceDict
from .v1_iscsi_persistent_volume_source import V1ISCSIPersistentVolumeSourceDict
from .v1_local_volume_source import V1LocalVolumeSourceDict
from .v1_nfs_volume_source import V1NFSVolumeSourceDict
from .v1_object_reference import V1ObjectReferenceDict
from .v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSourceDict
from .v1_portworx_volume_source import V1PortworxVolumeSourceDict
from .v1_quobyte_volume_source import V1QuobyteVolumeSourceDict
from .v1_rbd_persistent_volume_source import V1RBDPersistentVolumeSourceDict
from .v1_scale_io_persistent_volume_source import V1ScaleIOPersistentVolumeSourceDict
from .v1_storage_os_persistent_volume_source import V1StorageOSPersistentVolumeSourceDict
from .v1_volume_node_affinity import V1VolumeNodeAffinityDict
from .v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSourceDict

V1PersistentVolumeSpecDict = TypedDict(
    "V1PersistentVolumeSpecDict",
    {
        "accessModes": List[str],
        "awsElasticBlockStore": V1AWSElasticBlockStoreVolumeSourceDict,
        "azureDisk": V1AzureDiskVolumeSourceDict,
        "azureFile": V1AzureFilePersistentVolumeSourceDict,
        "capacity": Dict[str, str],
        "cephfs": V1CephFSPersistentVolumeSourceDict,
        "cinder": V1CinderPersistentVolumeSourceDict,
        "claimRef": V1ObjectReferenceDict,
        "csi": V1CSIPersistentVolumeSourceDict,
        "fc": V1FCVolumeSourceDict,
        "flexVolume": V1FlexPersistentVolumeSourceDict,
        "flocker": V1FlockerVolumeSourceDict,
        "gcePersistentDisk": V1GCEPersistentDiskVolumeSourceDict,
        "glusterfs": V1GlusterfsPersistentVolumeSourceDict,
        "hostPath": V1HostPathVolumeSourceDict,
        "iscsi": V1ISCSIPersistentVolumeSourceDict,
        "local": V1LocalVolumeSourceDict,
        "mountOptions": List[str],
        "nfs": V1NFSVolumeSourceDict,
        "nodeAffinity": V1VolumeNodeAffinityDict,
        "persistentVolumeReclaimPolicy": str,
        "photonPersistentDisk": V1PhotonPersistentDiskVolumeSourceDict,
        "portworxVolume": V1PortworxVolumeSourceDict,
        "quobyte": V1QuobyteVolumeSourceDict,
        "rbd": V1RBDPersistentVolumeSourceDict,
        "scaleIO": V1ScaleIOPersistentVolumeSourceDict,
        "storageClassName": str,
        "storageos": V1StorageOSPersistentVolumeSourceDict,
        "volumeMode": str,
        "vsphereVolume": V1VsphereVirtualDiskVolumeSourceDict,
    },
    total=False,
)
