# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1PodAffinityTermDict, V1WeightedPodAffinityTermDict

V1PodAntiAffinityDict = TypedDict(
    "V1PodAntiAffinityDict",
    {
        "preferredDuringSchedulingIgnoredDuringExecution": List[V1WeightedPodAffinityTermDict],
        "requiredDuringSchedulingIgnoredDuringExecution": List[V1PodAffinityTermDict],
    },
    total=False,
)