# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_persistent_volume_spec import V1PersistentVolumeSpecDict
from kubernetes_typed.client.models.v1_persistent_volume_status import V1PersistentVolumeStatusDict

V1PersistentVolumeDict = TypedDict(
    "V1PersistentVolumeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1PersistentVolumeSpecDict,
        "status": V1PersistentVolumeStatusDict,
    },
    total=False,
)
