# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProjectedVolumeSourceDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1VolumeProjectionDict

V1ProjectedVolumeSourceDict = TypedDict(
    "V1ProjectedVolumeSourceDict",
    {
        "defaultMode": int,
        "sources": List[V1VolumeProjectionDict],
    },
    total=False,
)
