# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1_persistent_volume_claim import V1PersistentVolumeClaimDict

V1PersistentVolumeClaimListDict = TypedDict(
    "V1PersistentVolumeClaimListDict",
    {
        "apiVersion": str,
        "items": List[V1PersistentVolumeClaimDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
