# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimStatusDict generated type."""
from typing import TypedDict, Dict, List

from .v1_persistent_volume_claim_condition import V1PersistentVolumeClaimConditionDict

V1PersistentVolumeClaimStatusDict = TypedDict(
    "V1PersistentVolumeClaimStatusDict",
    {
        "accessModes": List[str],
        "capacity": Dict[str, str],
        "conditions": List[V1PersistentVolumeClaimConditionDict],
        "phase": str,
    },
    total=False,
)
