# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodSpecDict generated type."""
from typing import TypedDict, Dict, List

from kubernetes_typed.client.models.v1_affinity import V1AffinityDict
from kubernetes_typed.client.models.v1_container import V1ContainerDict
from kubernetes_typed.client.models.v1_pod_dns_config import V1PodDNSConfigDict
from kubernetes_typed.client.models.v1_ephemeral_container import V1EphemeralContainerDict
from kubernetes_typed.client.models.v1_host_alias import V1HostAliasDict
from kubernetes_typed.client.models.v1_local_object_reference import V1LocalObjectReferenceDict
from kubernetes_typed.client.models.v1_pod_readiness_gate import V1PodReadinessGateDict
from kubernetes_typed.client.models.v1_pod_security_context import V1PodSecurityContextDict
from kubernetes_typed.client.models.v1_toleration import V1TolerationDict
from kubernetes_typed.client.models.v1_topology_spread_constraint import V1TopologySpreadConstraintDict
from kubernetes_typed.client.models.v1_volume import V1VolumeDict

V1PodSpecDict = TypedDict(
    "V1PodSpecDict",
    {
        "activeDeadlineSeconds": int,
        "affinity": V1AffinityDict,
        "automountServiceAccountToken": bool,
        "containers": List[V1ContainerDict],
        "dnsConfig": V1PodDNSConfigDict,
        "dnsPolicy": str,
        "enableServiceLinks": bool,
        "ephemeralContainers": List[V1EphemeralContainerDict],
        "hostAliases": List[V1HostAliasDict],
        "hostIPC": bool,
        "hostNetwork": bool,
        "hostPID": bool,
        "hostname": str,
        "imagePullSecrets": List[V1LocalObjectReferenceDict],
        "initContainers": List[V1ContainerDict],
        "nodeName": str,
        "nodeSelector": Dict[str, str],
        "overhead": Dict[str, str],
        "preemptionPolicy": str,
        "priority": int,
        "priorityClassName": str,
        "readinessGates": List[V1PodReadinessGateDict],
        "restartPolicy": str,
        "runtimeClassName": str,
        "schedulerName": str,
        "securityContext": V1PodSecurityContextDict,
        "serviceAccount": str,
        "serviceAccountName": str,
        "shareProcessNamespace": bool,
        "subdomain": str,
        "terminationGracePeriodSeconds": int,
        "tolerations": List[V1TolerationDict],
        "topologySpreadConstraints": List[V1TopologySpreadConstraintDict],
        "volumes": List[V1VolumeDict],
    },
    total=False,
)
