# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1ObjectMetaDict, V1PodSpecDict

V1PodTemplateSpecDict = TypedDict(
    "V1PodTemplateSpecDict",
    {
        "metadata": V1ObjectMetaDict,
        "spec": V1PodSpecDict,
    },
    total=False,
)