# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimSpecDict generated type."""
from typing import TypedDict, List

from .v1_label_selector import V1LabelSelectorDict
from .v1_resource_requirements import V1ResourceRequirementsDict
from .v1_typed_local_object_reference import V1TypedLocalObjectReferenceDict

V1PersistentVolumeClaimSpecDict = TypedDict(
    "V1PersistentVolumeClaimSpecDict",
    {
        "accessModes": List[str],
        "dataSource": V1TypedLocalObjectReferenceDict,
        "resources": V1ResourceRequirementsDict,
        "selector": V1LabelSelectorDict,
        "storageClassName": str,
        "volumeMode": str,
        "volumeName": str,
    },
    total=False,
)
