# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodIPDict generated type."""
from typing import TypedDict

V1PodIPDict = TypedDict(
    "V1PodIPDict",
    {
        "ip": str,
    },
    total=False,
)
