# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ProbeDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_exec_action import V1ExecActionDict
from kubernetes_typed.client.models.v1_http_get_action import V1HTTPGetActionDict
from kubernetes_typed.client.models.v1_tcp_socket_action import V1TCPSocketActionDict

V1ProbeDict = TypedDict(
    "V1ProbeDict",
    {
        "exec": V1ExecActionDict,
        "failureThreshold": int,
        "httpGet": V1HTTPGetActionDict,
        "initialDelaySeconds": int,
        "periodSeconds": int,
        "successThreshold": int,
        "tcpSocket": V1TCPSocketActionDict,
        "timeoutSeconds": int,
    },
    total=False,
)
