# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1LabelSelectorDict

V1PodAffinityTermDict = TypedDict(
    "V1PodAffinityTermDict",
    {
        "labelSelector": V1LabelSelectorDict,
        "namespaces": List[str],
        "topologyKey": str,
    },
    total=False,
)
