# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodTemplateSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_pod_spec import V1PodSpecDict

V1PodTemplateSpecDict = TypedDict(
    "V1PodTemplateSpecDict",
    {
        "metadata": V1ObjectMetaDict,
        "spec": V1PodSpecDict,
    },
    total=False,
)
