# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PersistentVolumeClaimSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1LabelSelectorDict, V1ResourceRequirementsDict, V1TypedLocalObjectReferenceDict

V1PersistentVolumeClaimSpecDict = TypedDict(
    "V1PersistentVolumeClaimSpecDict",
    {
        "accessModes": List[str],
        "dataSource": V1TypedLocalObjectReferenceDict,
        "resources": V1ResourceRequirementsDict,
        "selector": V1LabelSelectorDict,
        "storageClassName": str,
        "volumeMode": str,
        "volumeName": str,
    },
    total=False,
)
