# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PreconditionsDict generated type."""
from typing import TypedDict

V1PreconditionsDict = TypedDict(
    "V1PreconditionsDict",
    {
        "resourceVersion": str,
        "uid": str,
    },
    total=False,
)
