# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1PersistentVolumeStatusDict = TypedDict(
    "V1PersistentVolumeStatusDict",
    {
        "message": str,
        "phase": str,
        "reason": str,
    },
    total=False,
)