# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1PodStatusDict generated type."""
import datetime
from typing import TypedDict, List

from .v1_container_status import V1ContainerStatusDict
from .v1_pod_condition import V1PodConditionDict
from .v1_pod_ip import V1PodIPDict

V1PodStatusDict = TypedDict(
    "V1PodStatusDict",
    {
        "conditions": List[V1PodConditionDict],
        "containerStatuses": List[V1ContainerStatusDict],
        "ephemeralContainerStatuses": List[V1ContainerStatusDict],
        "hostIP": str,
        "initContainerStatuses": List[V1ContainerStatusDict],
        "message": str,
        "nominatedNodeName": str,
        "phase": str,
        "podIP": str,
        "podIPs": List[V1PodIPDict],
        "qosClass": str,
        "reason": str,
        "startTime": datetime.datetime,
    },
    total=False,
)
