# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1QuobyteVolumeSourceDict generated type."""
from typing import TypedDict

V1QuobyteVolumeSourceDict = TypedDict(
    "V1QuobyteVolumeSourceDict",
    {
        "group": str,
        "readOnly": bool,
        "registry": str,
        "tenant": str,
        "user": str,
        "volume": str,
    },
    total=False,
)
