# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1ListMetaDict, V1ResourceQuotaDict

V1ResourceQuotaListDict = TypedDict(
    "V1ResourceQuotaListDict",
    {
        "apiVersion": str,
        "items": List[V1ResourceQuotaDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)