# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerConditionDict generated type."""
import datetime
from typing import TypedDict

V1ReplicationControllerConditionDict = TypedDict(
    "V1ReplicationControllerConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
