# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerStatusDict generated type."""
from typing import TypedDict, List

from .v1_replication_controller_condition import V1ReplicationControllerConditionDict

V1ReplicationControllerStatusDict = TypedDict(
    "V1ReplicationControllerStatusDict",
    {
        "availableReplicas": int,
        "conditions": List[V1ReplicationControllerConditionDict],
        "fullyLabeledReplicas": int,
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
    },
    total=False,
)
