# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_replication_controller_spec import V1ReplicationControllerSpecDict
from kubernetes_typed.client.models.v1_replication_controller_status import V1ReplicationControllerStatusDict

V1ReplicationControllerDict = TypedDict(
    "V1ReplicationControllerDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ReplicationControllerSpecDict,
        "status": V1ReplicationControllerStatusDict,
    },
    total=False,
)
