# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaSpecDict generated type."""
from typing import TypedDict, Dict, List

from kubernetes_typed.client import V1ScopeSelectorDict

V1ResourceQuotaSpecDict = TypedDict(
    "V1ResourceQuotaSpecDict",
    {
        "hard": Dict[str, str],
        "scopeSelector": V1ScopeSelectorDict,
        "scopes": List[str],
    },
    total=False,
)
