# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceAttributesDict generated type."""
from typing import TypedDict

V1ResourceAttributesDict = TypedDict(
    "V1ResourceAttributesDict",
    {
        "group": str,
        "name": str,
        "namespace": str,
        "resource": str,
        "subresource": str,
        "verb": str,
        "version": str,
    },
    total=False,
)
