# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleBindingDict generated type."""
from typing import TypedDict, List

from .v1_object_meta import V1ObjectMetaDict
from .v1_role_ref import V1RoleRefDict
from .v1_subject import V1SubjectDict

V1RoleBindingDict = TypedDict(
    "V1RoleBindingDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "roleRef": V1RoleRefDict,
        "subjects": List[V1SubjectDict],
    },
    total=False,
)
