# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleRefDict generated type."""
from typing import TypedDict

V1RoleRefDict = TypedDict(
    "V1RoleRefDict",
    {
        "apiGroup": str,
        "kind": str,
        "name": str,
    },
    total=False,
)
