# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1ResourceQuotaSpecDict, V1ResourceQuotaStatusDict

V1ResourceQuotaDict = TypedDict(
    "V1ResourceQuotaDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ResourceQuotaSpecDict,
        "status": V1ResourceQuotaStatusDict,
    },
    total=False,
)
