# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_replica_set_spec import V1ReplicaSetSpecDict
from kubernetes_typed.client.models.v1_replica_set_status import V1ReplicaSetStatusDict

V1ReplicaSetDict = TypedDict(
    "V1ReplicaSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ReplicaSetSpecDict,
        "status": V1ReplicaSetStatusDict,
    },
    total=False,
)
