# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceQuotaListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_resource_quota import V1ResourceQuotaDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1ResourceQuotaListDict = TypedDict(
    "V1ResourceQuotaListDict",
    {
        "apiVersion": str,
        "items": List[V1ResourceQuotaDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
