# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleBindingListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1RoleBindingDict

V1RoleBindingListDict = TypedDict(
    "V1RoleBindingListDict",
    {
        "apiVersion": str,
        "items": List[V1RoleBindingDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
