# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RBDPersistentVolumeSourceDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1SecretReferenceDict

V1RBDPersistentVolumeSourceDict = TypedDict(
    "V1RBDPersistentVolumeSourceDict",
    {
        "fsType": str,
        "image": str,
        "keyring": str,
        "monitors": List[str],
        "pool": str,
        "readOnly": bool,
        "secretRef": V1SecretReferenceDict,
        "user": str,
    },
    total=False,
)
