# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1ReplicationControllerDict

V1ReplicationControllerListDict = TypedDict(
    "V1ReplicationControllerListDict",
    {
        "apiVersion": str,
        "items": List[V1ReplicationControllerDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
