# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1RollingUpdateDeploymentDict = TypedDict(
    "V1RollingUpdateDeploymentDict",
    {
        "maxSurge": object,
        "maxUnavailable": object,
    },
    total=False,
)