# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RollingUpdateDeploymentDict generated type."""
from typing import TypedDict

V1RollingUpdateDeploymentDict = TypedDict(
    "V1RollingUpdateDeploymentDict",
    {
        "maxSurge": object,
        "maxUnavailable": object,
    },
    total=False,
)
