# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ResourceFieldSelectorDict generated type."""
from typing import TypedDict

V1ResourceFieldSelectorDict = TypedDict(
    "V1ResourceFieldSelectorDict",
    {
        "containerName": str,
        "divisor": str,
        "resource": str,
    },
    total=False,
)
