# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1ResourceFieldSelectorDict = TypedDict(
    "V1ResourceFieldSelectorDict",
    {
        "containerName": str,
        "divisor": str,
        "resource": str,
    },
    total=False,
)