# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ReplicaSetConditionDict

V1ReplicaSetStatusDict = TypedDict(
    "V1ReplicaSetStatusDict",
    {
        "availableReplicas": int,
        "conditions": List[V1ReplicaSetConditionDict],
        "fullyLabeledReplicas": int,
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
    },
    total=False,
)
