# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicationControllerListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1_replication_controller import V1ReplicationControllerDict

V1ReplicationControllerListDict = TypedDict(
    "V1ReplicationControllerListDict",
    {
        "apiVersion": str,
        "items": List[V1ReplicationControllerDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
