# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ReplicaSetDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1ReplicaSetSpecDict, V1ReplicaSetStatusDict

V1ReplicaSetDict = TypedDict(
    "V1ReplicaSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ReplicaSetSpecDict,
        "status": V1ReplicaSetStatusDict,
    },
    total=False,
)
