# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1RoleDict generated type."""
from typing import TypedDict, List

from .v1_object_meta import V1ObjectMetaDict
from .v1_policy_rule import V1PolicyRuleDict

V1RoleDict = TypedDict(
    "V1RoleDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "rules": List[V1PolicyRuleDict],
    },
    total=False,
)
