# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectDict generated type."""
from typing import TypedDict

V1SubjectDict = TypedDict(
    "V1SubjectDict",
    {
        "apiGroup": str,
        "kind": str,
        "name": str,
        "namespace": str,
    },
    total=False,
)
