# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretReferenceDict generated type."""
from typing import TypedDict

V1SecretReferenceDict = TypedDict(
    "V1SecretReferenceDict",
    {
        "name": str,
        "namespace": str,
    },
    total=False,
)
