# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ClientIPConfigDict

V1SessionAffinityConfigDict = TypedDict(
    "V1SessionAffinityConfigDict",
    {
        "clientIP": V1ClientIPConfigDict,
    },
    total=False,
)
