# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_scale_spec import V1ScaleSpecDict
from kubernetes_typed.client.models.v1_scale_status import V1ScaleStatusDict

V1ScaleDict = TypedDict(
    "V1ScaleDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ScaleSpecDict,
        "status": V1ScaleStatusDict,
    },
    total=False,
)
