# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1SecretKeySelectorDict = TypedDict(
    "V1SecretKeySelectorDict",
    {
        "key": str,
        "name": str,
        "optional": bool,
    },
    total=False,
)
