# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1ObjectReferenceDict

V1StorageOSPersistentVolumeSourceDict = TypedDict(
    "V1StorageOSPersistentVolumeSourceDict",
    {
        "fsType": str,
        "readOnly": bool,
        "secretRef": V1ObjectReferenceDict,
        "volumeName": str,
        "volumeNamespace": str,
    },
    total=False,
)