# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1ServicePortDict = TypedDict(
    "V1ServicePortDict",
    {
        "name": str,
        "nodePort": int,
        "port": int,
        "protocol": str,
        "targetPort": object,
    },
    total=False,
)