# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LoadBalancerStatusDict

V1ServiceStatusDict = TypedDict(
    "V1ServiceStatusDict",
    {
        "loadBalancer": V1LoadBalancerStatusDict,
    },
    total=False,
)
