# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageOSPersistentVolumeSourceDict generated type."""
from typing import TypedDict

from .v1_object_reference import V1ObjectReferenceDict

V1StorageOSPersistentVolumeSourceDict = TypedDict(
    "V1StorageOSPersistentVolumeSourceDict",
    {
        "fsType": str,
        "readOnly": bool,
        "secretRef": V1ObjectReferenceDict,
        "volumeName": str,
        "volumeNamespace": str,
    },
    total=False,
)
