# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleSpecDict generated type."""
from typing import TypedDict

V1ScaleSpecDict = TypedDict(
    "V1ScaleSpecDict",
    {
        "replicas": int,
    },
    total=False,
)
