# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecretEnvSourceDict generated type."""
from typing import TypedDict

V1SecretEnvSourceDict = TypedDict(
    "V1SecretEnvSourceDict",
    {
        "name": str,
        "optional": bool,
    },
    total=False,
)
