# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SessionAffinityConfigDict generated type."""
from typing import TypedDict

from .v1_client_ip_config import V1ClientIPConfigDict

V1SessionAffinityConfigDict = TypedDict(
    "V1SessionAffinityConfigDict",
    {
        "clientIP": V1ClientIPConfigDict,
    },
    total=False,
)
