# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectAccessReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1SelfSubjectAccessReviewSpecDict, V1SubjectAccessReviewStatusDict

V1SelfSubjectAccessReviewDict = TypedDict(
    "V1SelfSubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1SelfSubjectAccessReviewSpecDict,
        "status": V1SubjectAccessReviewStatusDict,
    },
    total=False,
)
