# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServerAddressByClientCIDRDict generated type."""
from typing import TypedDict

V1ServerAddressByClientCIDRDict = TypedDict(
    "V1ServerAddressByClientCIDRDict",
    {
        "clientCIDR": str,
        "serverAddress": str,
    },
    total=False,
)
