# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_service_account import V1ServiceAccountDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1ServiceAccountListDict = TypedDict(
    "V1ServiceAccountListDict",
    {
        "apiVersion": str,
        "items": List[V1ServiceAccountDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
