# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceAccountDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1LocalObjectReferenceDict, V1ObjectMetaDict, V1ObjectReferenceDict

V1ServiceAccountDict = TypedDict(
    "V1ServiceAccountDict",
    {
        "apiVersion": str,
        "automountServiceAccountToken": bool,
        "imagePullSecrets": List[V1LocalObjectReferenceDict],
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "secrets": List[V1ObjectReferenceDict],
    },
    total=False,
)
