# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatusCauseDict generated type."""
from typing import TypedDict

V1StatusCauseDict = TypedDict(
    "V1StatusCauseDict",
    {
        "field": str,
        "message": str,
        "reason": str,
    },
    total=False,
)
