# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScaleIOVolumeSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LocalObjectReferenceDict

V1ScaleIOVolumeSourceDict = TypedDict(
    "V1ScaleIOVolumeSourceDict",
    {
        "fsType": str,
        "gateway": str,
        "protectionDomain": str,
        "readOnly": bool,
        "secretRef": V1LocalObjectReferenceDict,
        "sslEnabled": bool,
        "storageMode": str,
        "storagePool": str,
        "system": str,
        "volumeName": str,
    },
    total=False,
)
