# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServicePortDict generated type."""
from typing import TypedDict

V1ServicePortDict = TypedDict(
    "V1ServicePortDict",
    {
        "appProtocol": str,
        "name": str,
        "nodePort": int,
        "port": int,
        "protocol": str,
        "targetPort": object,
    },
    total=False,
)
