# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectRulesReviewSpecDict generated type."""
from typing import TypedDict

V1SelfSubjectRulesReviewSpecDict = TypedDict(
    "V1SelfSubjectRulesReviewSpecDict",
    {
        "namespace": str,
    },
    total=False,
)
