# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageClassDict generated type."""
from typing import TypedDict, Dict, List

from kubernetes_typed.client import V1ObjectMetaDict, V1TopologySelectorTermDict

V1StorageClassDict = TypedDict(
    "V1StorageClassDict",
    {
        "allowVolumeExpansion": bool,
        "allowedTopologies": List[V1TopologySelectorTermDict],
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "mountOptions": List[str],
        "parameters": Dict[str, str],
        "provisioner": str,
        "reclaimPolicy": str,
        "volumeBindingMode": str,
    },
    total=False,
)
