# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1ScaleStatusDict = TypedDict(
    "V1ScaleStatusDict",
    {
        "replicas": int,
        "selector": str,
    },
    total=False,
)
