# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorDict
from kubernetes_typed.client.models.v1_pod_template_spec import V1PodTemplateSpecDict
from kubernetes_typed.client.models.v1_stateful_set_update_strategy import V1StatefulSetUpdateStrategyDict
from kubernetes_typed.client.models.v1_persistent_volume_claim import V1PersistentVolumeClaimDict

V1StatefulSetSpecDict = TypedDict(
    "V1StatefulSetSpecDict",
    {
        "podManagementPolicy": str,
        "replicas": int,
        "revisionHistoryLimit": int,
        "selector": V1LabelSelectorDict,
        "serviceName": str,
        "template": V1PodTemplateSpecDict,
        "updateStrategy": V1StatefulSetUpdateStrategyDict,
        "volumeClaimTemplates": List[V1PersistentVolumeClaimDict],
    },
    total=False,
)
