# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SecurityContextDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_capabilities import V1CapabilitiesDict
from kubernetes_typed.client.models.v1_se_linux_options import V1SELinuxOptionsDict
from kubernetes_typed.client.models.v1_windows_security_context_options import V1WindowsSecurityContextOptionsDict

V1SecurityContextDict = TypedDict(
    "V1SecurityContextDict",
    {
        "allowPrivilegeEscalation": bool,
        "capabilities": V1CapabilitiesDict,
        "privileged": bool,
        "procMount": str,
        "readOnlyRootFilesystem": bool,
        "runAsGroup": int,
        "runAsNonRoot": bool,
        "runAsUser": int,
        "seLinuxOptions": V1SELinuxOptionsDict,
        "windowsOptions": V1WindowsSecurityContextOptionsDict,
    },
    total=False,
)
