# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SubjectAccessReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1SubjectAccessReviewSpecDict, V1SubjectAccessReviewStatusDict

V1SubjectAccessReviewDict = TypedDict(
    "V1SubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1SubjectAccessReviewSpecDict,
        "status": V1SubjectAccessReviewStatusDict,
    },
    total=False,
)
