# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetUpdateStrategyDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1RollingUpdateStatefulSetStrategyDict

V1StatefulSetUpdateStrategyDict = TypedDict(
    "V1StatefulSetUpdateStrategyDict",
    {
        "rollingUpdate": V1RollingUpdateStatefulSetStrategyDict,
        "type": str,
    },
    total=False,
)
