# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ServiceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1ServiceSpecDict, V1ServiceStatusDict

V1ServiceDict = TypedDict(
    "V1ServiceDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1ServiceSpecDict,
        "status": V1ServiceStatusDict,
    },
    total=False,
)
