# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StorageOSVolumeSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LocalObjectReferenceDict

V1StorageOSVolumeSourceDict = TypedDict(
    "V1StorageOSVolumeSourceDict",
    {
        "fsType": str,
        "readOnly": bool,
        "secretRef": V1LocalObjectReferenceDict,
        "volumeName": str,
        "volumeNamespace": str,
    },
    total=False,
)
