# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1_stateful_set import V1StatefulSetDict

V1StatefulSetListDict = TypedDict(
    "V1StatefulSetListDict",
    {
        "apiVersion": str,
        "items": List[V1StatefulSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
