# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopeSelectorDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_scoped_resource_selector_requirement import V1ScopedResourceSelectorRequirementDict

V1ScopeSelectorDict = TypedDict(
    "V1ScopeSelectorDict",
    {
        "matchExpressions": List[V1ScopedResourceSelectorRequirementDict],
    },
    total=False,
)
