# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ScopedResourceSelectorRequirementDict generated type."""
from typing import TypedDict, List

V1ScopedResourceSelectorRequirementDict = TypedDict(
    "V1ScopedResourceSelectorRequirementDict",
    {
        "operator": str,
        "scopeName": str,
        "values": List[str],
    },
    total=False,
)
