# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SelfSubjectRulesReviewDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1_self_subject_rules_review_spec import V1SelfSubjectRulesReviewSpecDict
from .v1_subject_rules_review_status import V1SubjectRulesReviewStatusDict

V1SelfSubjectRulesReviewDict = TypedDict(
    "V1SelfSubjectRulesReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1SelfSubjectRulesReviewSpecDict,
        "status": V1SubjectRulesReviewStatusDict,
    },
    total=False,
)
