# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetConditionDict generated type."""
import datetime
from typing import TypedDict

V1StatefulSetConditionDict = TypedDict(
    "V1StatefulSetConditionDict",
    {
        "lastTransitionTime": datetime.datetime,
        "message": str,
        "reason": str,
        "status": str,
        "type": str,
    },
    total=False,
)
