# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1StatefulSetSpecDict, V1StatefulSetStatusDict

V1StatefulSetDict = TypedDict(
    "V1StatefulSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1StatefulSetSpecDict,
        "status": V1StatefulSetStatusDict,
    },
    total=False,
)
