# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1StatefulSetDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1_stateful_set_spec import V1StatefulSetSpecDict
from .v1_stateful_set_status import V1StatefulSetStatusDict

V1StatefulSetDict = TypedDict(
    "V1StatefulSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1StatefulSetSpecDict,
        "status": V1StatefulSetStatusDict,
    },
    total=False,
)
