# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1SELinuxOptionsDict generated type."""
from typing import TypedDict

V1SELinuxOptionsDict = TypedDict(
    "V1SELinuxOptionsDict",
    {
        "level": str,
        "role": str,
        "type": str,
        "user": str,
    },
    total=False,
)
