# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1TCPSocketActionDict = TypedDict(
    "V1TCPSocketActionDict",
    {
        "host": str,
        "port": object,
    },
    total=False,
)