# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1TopologySelectorLabelRequirementDict

V1TopologySelectorTermDict = TypedDict(
    "V1TopologySelectorTermDict",
    {
        "matchLabelExpressions": List[V1TopologySelectorLabelRequirementDict],
    },
    total=False,
)
