# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewSpecDict generated type."""
from typing import TypedDict, List

V1TokenReviewSpecDict = TypedDict(
    "V1TokenReviewSpecDict",
    {
        "audiences": List[str],
        "token": str,
    },
    total=False,
)
