# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TopologySelectorLabelRequirementDict generated type."""
from typing import TypedDict, List

V1TopologySelectorLabelRequirementDict = TypedDict(
    "V1TopologySelectorLabelRequirementDict",
    {
        "key": str,
        "values": List[str],
    },
    total=False,
)
