# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1TokenReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1TokenReviewSpecDict, V1TokenReviewStatusDict

V1TokenReviewDict = TypedDict(
    "V1TokenReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1TokenReviewSpecDict,
        "status": V1TokenReviewStatusDict,
    },
    total=False,
)
