# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1BoundObjectReferenceDict

V1TokenRequestSpecDict = TypedDict(
    "V1TokenRequestSpecDict",
    {
        "audiences": List[str],
        "boundObjectRef": V1BoundObjectReferenceDict,
        "expirationSeconds": int,
    },
    total=False,
)
