# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1UserInfoDict generated type."""
from typing import TypedDict, Dict, List

V1UserInfoDict = TypedDict(
    "V1UserInfoDict",
    {
        "extra": Dict[str, List[str]],
        "groups": List[str],
        "uid": str,
        "username": str,
    },
    total=False,
)
