# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_persistent_volume_spec import V1PersistentVolumeSpecDict

V1VolumeAttachmentSourceDict = TypedDict(
    "V1VolumeAttachmentSourceDict",
    {
        "inlineVolumeSpec": V1PersistentVolumeSpecDict,
        "persistentVolumeName": str,
    },
    total=False,
)
