# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1_volume_attachment_spec import V1VolumeAttachmentSpecDict
from kubernetes_typed.client.models.v1_volume_attachment_status import V1VolumeAttachmentStatusDict

V1VolumeAttachmentDict = TypedDict(
    "V1VolumeAttachmentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1VolumeAttachmentSpecDict,
        "status": V1VolumeAttachmentStatusDict,
    },
    total=False,
)
