# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VsphereVirtualDiskVolumeSourceDict generated type."""
from typing import TypedDict

V1VsphereVirtualDiskVolumeSourceDict = TypedDict(
    "V1VsphereVirtualDiskVolumeSourceDict",
    {
        "fsType": str,
        "storagePolicyID": str,
        "storagePolicyName": str,
        "volumePath": str,
    },
    total=False,
)
