# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeErrorDict generated type."""
import datetime
from typing import TypedDict

V1VolumeErrorDict = TypedDict(
    "V1VolumeErrorDict",
    {
        "message": str,
        "time": datetime.datetime,
    },
    total=False,
)
