# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import AdmissionregistrationV1WebhookClientConfigDict, V1LabelSelectorDict, V1RuleWithOperationsDict

V1ValidatingWebhookDict = TypedDict(
    "V1ValidatingWebhookDict",
    {
        "admissionReviewVersions": List[str],
        "clientConfig": AdmissionregistrationV1WebhookClientConfigDict,
        "failurePolicy": str,
        "matchPolicy": str,
        "name": str,
        "namespaceSelector": V1LabelSelectorDict,
        "objectSelector": V1LabelSelectorDict,
        "rules": List[V1RuleWithOperationsDict],
        "sideEffects": str,
        "timeoutSeconds": int,
    },
    total=False,
)
