# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_aws_elastic_block_store_volume_source import V1AWSElasticBlockStoreVolumeSourceDict
from kubernetes_typed.client.models.v1_azure_disk_volume_source import V1AzureDiskVolumeSourceDict
from kubernetes_typed.client.models.v1_azure_file_volume_source import V1AzureFileVolumeSourceDict
from kubernetes_typed.client.models.v1_ceph_fs_volume_source import V1CephFSVolumeSourceDict
from kubernetes_typed.client.models.v1_cinder_volume_source import V1CinderVolumeSourceDict
from kubernetes_typed.client.models.v1_config_map_volume_source import V1ConfigMapVolumeSourceDict
from kubernetes_typed.client.models.v1_csi_volume_source import V1CSIVolumeSourceDict
from kubernetes_typed.client.models.v1_downward_api_volume_source import V1DownwardAPIVolumeSourceDict
from kubernetes_typed.client.models.v1_empty_dir_volume_source import V1EmptyDirVolumeSourceDict
from kubernetes_typed.client.models.v1_fc_volume_source import V1FCVolumeSourceDict
from kubernetes_typed.client.models.v1_flex_volume_source import V1FlexVolumeSourceDict
from kubernetes_typed.client.models.v1_flocker_volume_source import V1FlockerVolumeSourceDict
from kubernetes_typed.client.models.v1_gce_persistent_disk_volume_source import V1GCEPersistentDiskVolumeSourceDict
from kubernetes_typed.client.models.v1_git_repo_volume_source import V1GitRepoVolumeSourceDict
from kubernetes_typed.client.models.v1_glusterfs_volume_source import V1GlusterfsVolumeSourceDict
from kubernetes_typed.client.models.v1_host_path_volume_source import V1HostPathVolumeSourceDict
from kubernetes_typed.client.models.v1_iscsi_volume_source import V1ISCSIVolumeSourceDict
from kubernetes_typed.client.models.v1_nfs_volume_source import V1NFSVolumeSourceDict
from kubernetes_typed.client.models.v1_persistent_volume_claim_volume_source import V1PersistentVolumeClaimVolumeSourceDict
from kubernetes_typed.client.models.v1_photon_persistent_disk_volume_source import V1PhotonPersistentDiskVolumeSourceDict
from kubernetes_typed.client.models.v1_portworx_volume_source import V1PortworxVolumeSourceDict
from kubernetes_typed.client.models.v1_projected_volume_source import V1ProjectedVolumeSourceDict
from kubernetes_typed.client.models.v1_quobyte_volume_source import V1QuobyteVolumeSourceDict
from kubernetes_typed.client.models.v1_rbd_volume_source import V1RBDVolumeSourceDict
from kubernetes_typed.client.models.v1_scale_io_volume_source import V1ScaleIOVolumeSourceDict
from kubernetes_typed.client.models.v1_secret_volume_source import V1SecretVolumeSourceDict
from kubernetes_typed.client.models.v1_storage_os_volume_source import V1StorageOSVolumeSourceDict
from kubernetes_typed.client.models.v1_vsphere_virtual_disk_volume_source import V1VsphereVirtualDiskVolumeSourceDict

V1VolumeDict = TypedDict(
    "V1VolumeDict",
    {
        "awsElasticBlockStore": V1AWSElasticBlockStoreVolumeSourceDict,
        "azureDisk": V1AzureDiskVolumeSourceDict,
        "azureFile": V1AzureFileVolumeSourceDict,
        "cephfs": V1CephFSVolumeSourceDict,
        "cinder": V1CinderVolumeSourceDict,
        "configMap": V1ConfigMapVolumeSourceDict,
        "csi": V1CSIVolumeSourceDict,
        "downwardAPI": V1DownwardAPIVolumeSourceDict,
        "emptyDir": V1EmptyDirVolumeSourceDict,
        "fc": V1FCVolumeSourceDict,
        "flexVolume": V1FlexVolumeSourceDict,
        "flocker": V1FlockerVolumeSourceDict,
        "gcePersistentDisk": V1GCEPersistentDiskVolumeSourceDict,
        "gitRepo": V1GitRepoVolumeSourceDict,
        "glusterfs": V1GlusterfsVolumeSourceDict,
        "hostPath": V1HostPathVolumeSourceDict,
        "iscsi": V1ISCSIVolumeSourceDict,
        "name": str,
        "nfs": V1NFSVolumeSourceDict,
        "persistentVolumeClaim": V1PersistentVolumeClaimVolumeSourceDict,
        "photonPersistentDisk": V1PhotonPersistentDiskVolumeSourceDict,
        "portworxVolume": V1PortworxVolumeSourceDict,
        "projected": V1ProjectedVolumeSourceDict,
        "quobyte": V1QuobyteVolumeSourceDict,
        "rbd": V1RBDVolumeSourceDict,
        "scaleIO": V1ScaleIOVolumeSourceDict,
        "secret": V1SecretVolumeSourceDict,
        "storageos": V1StorageOSVolumeSourceDict,
        "vsphereVolume": V1VsphereVirtualDiskVolumeSourceDict,
    },
    total=False,
)
