# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1ValidatingWebhookConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_validating_webhook_configuration import V1ValidatingWebhookConfigurationDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1ValidatingWebhookConfigurationListDict = TypedDict(
    "V1ValidatingWebhookConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1ValidatingWebhookConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
