# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentSpecDict generated type."""
from typing import TypedDict

from .v1_volume_attachment_source import V1VolumeAttachmentSourceDict

V1VolumeAttachmentSpecDict = TypedDict(
    "V1VolumeAttachmentSpecDict",
    {
        "attacher": str,
        "nodeName": str,
        "source": V1VolumeAttachmentSourceDict,
    },
    total=False,
)
