# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeDeviceDict generated type."""
from typing import TypedDict

V1VolumeDeviceDict = TypedDict(
    "V1VolumeDeviceDict",
    {
        "devicePath": str,
        "name": str,
    },
    total=False,
)
