# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeProjectionDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ConfigMapProjectionDict, V1DownwardAPIProjectionDict, V1SecretProjectionDict, V1ServiceAccountTokenProjectionDict

V1VolumeProjectionDict = TypedDict(
    "V1VolumeProjectionDict",
    {
        "configMap": V1ConfigMapProjectionDict,
        "downwardAPI": V1DownwardAPIProjectionDict,
        "secret": V1SecretProjectionDict,
        "serviceAccountToken": V1ServiceAccountTokenProjectionDict,
    },
    total=False,
)
