# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentStatusDict generated type."""
from typing import TypedDict, Dict

from kubernetes_typed.client import V1VolumeErrorDict

V1VolumeAttachmentStatusDict = TypedDict(
    "V1VolumeAttachmentStatusDict",
    {
        "attachError": V1VolumeErrorDict,
        "attached": bool,
        "attachmentMetadata": Dict[str, str],
        "detachError": V1VolumeErrorDict,
    },
    total=False,
)
