# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeAttachmentListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_volume_attachment import V1VolumeAttachmentDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1VolumeAttachmentListDict = TypedDict(
    "V1VolumeAttachmentListDict",
    {
        "apiVersion": str,
        "items": List[V1VolumeAttachmentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
