# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1VolumeMountDict generated type."""
from typing import TypedDict

V1VolumeMountDict = TypedDict(
    "V1VolumeMountDict",
    {
        "mountPath": str,
        "mountPropagation": str,
        "name": str,
        "readOnly": bool,
        "subPath": str,
        "subPathExpr": str,
    },
    total=False,
)
