# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WatchEventDict generated type."""
from typing import TypedDict

V1WatchEventDict = TypedDict(
    "V1WatchEventDict",
    {
        "object": object,
        "type": str,
    },
    total=False,
)
