# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WebhookConversionDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import ApiextensionsV1WebhookClientConfigDict

V1WebhookConversionDict = TypedDict(
    "V1WebhookConversionDict",
    {
        "clientConfig": ApiextensionsV1WebhookClientConfigDict,
        "conversionReviewVersions": List[str],
    },
    total=False,
)
