# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1WindowsSecurityContextOptionsDict generated type."""
from typing import TypedDict

V1WindowsSecurityContextOptionsDict = TypedDict(
    "V1WindowsSecurityContextOptionsDict",
    {
        "gmsaCredentialSpec": str,
        "gmsaCredentialSpecName": str,
        "runAsUserName": str,
    },
    total=False,
)
