# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1FlowSchemaStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1alpha1FlowSchemaConditionDict

V1alpha1FlowSchemaStatusDict = TypedDict(
    "V1alpha1FlowSchemaStatusDict",
    {
        "conditions": List[V1alpha1FlowSchemaConditionDict],
    },
    total=False,
)
