# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1FlowDistinguisherMethodDict generated type."""
from typing import TypedDict

V1alpha1FlowDistinguisherMethodDict = TypedDict(
    "V1alpha1FlowDistinguisherMethodDict",
    {
        "type": str,
    },
    total=False,
)
