# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1RoleDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ObjectMetaDict, V1alpha1PolicyRuleDict

V1alpha1RoleDict = TypedDict(
    "V1alpha1RoleDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "rules": List[V1alpha1PolicyRuleDict],
    },
    total=False,
)
