# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1alpha1ServiceAccountSubjectDict = TypedDict(
    "V1alpha1ServiceAccountSubjectDict",
    {
        "name": str,
        "namespace": str,
    },
    total=False,
)