# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1alpha1GroupSubjectDict = TypedDict(
    "V1alpha1GroupSubjectDict",
    {
        "name": str,
    },
    total=False,
)