# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1OverheadDict generated type."""
from typing import TypedDict, Dict

V1alpha1OverheadDict = TypedDict(
    "V1alpha1OverheadDict",
    {
        "podFixed": Dict[str, str],
    },
    total=False,
)
