# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

V1alpha1ResourcePolicyRuleDict = TypedDict(
    "V1alpha1ResourcePolicyRuleDict",
    {
        "apiGroups": List[str],
        "clusterScope": bool,
        "namespaces": List[str],
        "resources": List[str],
        "verbs": List[str],
    },
    total=False,
)
