# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttachmentSourceDict generated type."""
from typing import TypedDict

from .v1_persistent_volume_spec import V1PersistentVolumeSpecDict

V1alpha1VolumeAttachmentSourceDict = TypedDict(
    "V1alpha1VolumeAttachmentSourceDict",
    {
        "inlineVolumeSpec": V1PersistentVolumeSpecDict,
        "persistentVolumeName": str,
    },
    total=False,
)
