# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterRoleBindingListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1alpha1_cluster_role_binding import V1alpha1ClusterRoleBindingDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1alpha1ClusterRoleBindingListDict = TypedDict(
    "V1alpha1ClusterRoleBindingListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1ClusterRoleBindingDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
