# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterRoleDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ObjectMetaDict, V1alpha1AggregationRuleDict, V1alpha1PolicyRuleDict

V1alpha1ClusterRoleDict = TypedDict(
    "V1alpha1ClusterRoleDict",
    {
        "aggregationRule": V1alpha1AggregationRuleDict,
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "rules": List[V1alpha1PolicyRuleDict],
    },
    total=False,
)
