# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1UserSubjectDict generated type."""
from typing import TypedDict

V1alpha1UserSubjectDict = TypedDict(
    "V1alpha1UserSubjectDict",
    {
        "name": str,
    },
    total=False,
)
