# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1FlowSchemaSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1alpha1FlowDistinguisherMethodDict, V1alpha1PolicyRulesWithSubjectsDict, V1alpha1PriorityLevelConfigurationReferenceDict

V1alpha1FlowSchemaSpecDict = TypedDict(
    "V1alpha1FlowSchemaSpecDict",
    {
        "distinguisherMethod": V1alpha1FlowDistinguisherMethodDict,
        "matchingPrecedence": int,
        "priorityLevelConfiguration": V1alpha1PriorityLevelConfigurationReferenceDict,
        "rules": List[V1alpha1PolicyRulesWithSubjectsDict],
    },
    total=False,
)
