# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1alpha1PriorityLevelConfigurationReferenceDict = TypedDict(
    "V1alpha1PriorityLevelConfigurationReferenceDict",
    {
        "name": str,
    },
    total=False,
)
