# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PriorityLevelConfigurationStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1alpha1PriorityLevelConfigurationConditionDict

V1alpha1PriorityLevelConfigurationStatusDict = TypedDict(
    "V1alpha1PriorityLevelConfigurationStatusDict",
    {
        "conditions": List[V1alpha1PriorityLevelConfigurationConditionDict],
    },
    total=False,
)
