# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttachmentDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1alpha1_volume_attachment_spec import V1alpha1VolumeAttachmentSpecDict
from kubernetes_typed.client.models.v1alpha1_volume_attachment_status import V1alpha1VolumeAttachmentStatusDict

V1alpha1VolumeAttachmentDict = TypedDict(
    "V1alpha1VolumeAttachmentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1alpha1VolumeAttachmentSpecDict,
        "status": V1alpha1VolumeAttachmentStatusDict,
    },
    total=False,
)
