# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict


V1alpha1VolumeErrorDict = TypedDict(
    "V1alpha1VolumeErrorDict",
    {
        "message": str,
        "time": datetime.datetime,
    },
    total=False,
)