# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1alpha1FlowDistinguisherMethodDict = TypedDict(
    "V1alpha1FlowDistinguisherMethodDict",
    {
        "type": str,
    },
    total=False,
)