# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PodPresetDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1alpha1_pod_preset_spec import V1alpha1PodPresetSpecDict

V1alpha1PodPresetDict = TypedDict(
    "V1alpha1PodPresetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1alpha1PodPresetSpecDict,
    },
    total=False,
)
