# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1WebhookThrottleConfigDict generated type."""
from typing import TypedDict

V1alpha1WebhookThrottleConfigDict = TypedDict(
    "V1alpha1WebhookThrottleConfigDict",
    {
        "burst": int,
        "qps": int,
    },
    total=False,
)
