# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1RoleBindingDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1alpha1_role_ref import V1alpha1RoleRefDict
from kubernetes_typed.client.models.rbac_v1alpha1_subject import RbacV1alpha1SubjectDict

V1alpha1RoleBindingDict = TypedDict(
    "V1alpha1RoleBindingDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "roleRef": V1alpha1RoleRefDict,
        "subjects": List[RbacV1alpha1SubjectDict],
    },
    total=False,
)
