# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttachmentListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1alpha1_volume_attachment import V1alpha1VolumeAttachmentDict

V1alpha1VolumeAttachmentListDict = TypedDict(
    "V1alpha1VolumeAttachmentListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1VolumeAttachmentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
