# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PodPresetListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1alpha1PodPresetDict

V1alpha1PodPresetListDict = TypedDict(
    "V1alpha1PodPresetListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1PodPresetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
