# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, Dict

from kubernetes_typed.client import V1alpha1VolumeErrorDict

V1alpha1VolumeAttachmentStatusDict = TypedDict(
    "V1alpha1VolumeAttachmentStatusDict",
    {
        "attachError": V1alpha1VolumeErrorDict,
        "attached": bool,
        "attachmentMetadata": Dict[str, str],
        "detachError": V1alpha1VolumeErrorDict,
    },
    total=False,
)
