# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1VolumeAttachmentListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1alpha1VolumeAttachmentDict

V1alpha1VolumeAttachmentListDict = TypedDict(
    "V1alpha1VolumeAttachmentListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1VolumeAttachmentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
