# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PolicyDict generated type."""
from typing import TypedDict, List

V1alpha1PolicyDict = TypedDict(
    "V1alpha1PolicyDict",
    {
        "level": str,
        "stages": List[str],
    },
    total=False,
)
