# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1RoleRefDict generated type."""
from typing import TypedDict

V1alpha1RoleRefDict = TypedDict(
    "V1alpha1RoleRefDict",
    {
        "apiGroup": str,
        "kind": str,
        "name": str,
    },
    total=False,
)
