# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1FlowSchemaListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1alpha1_flow_schema import V1alpha1FlowSchemaDict

V1alpha1FlowSchemaListDict = TypedDict(
    "V1alpha1FlowSchemaListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1FlowSchemaDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
