# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ClusterRoleDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1alpha1_aggregation_rule import V1alpha1AggregationRuleDict
from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1alpha1_policy_rule import V1alpha1PolicyRuleDict

V1alpha1ClusterRoleDict = TypedDict(
    "V1alpha1ClusterRoleDict",
    {
        "aggregationRule": V1alpha1AggregationRuleDict,
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "rules": List[V1alpha1PolicyRuleDict],
    },
    total=False,
)
