# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PolicyRulesWithSubjectsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1alpha1_non_resource_policy_rule import V1alpha1NonResourcePolicyRuleDict
from kubernetes_typed.client.models.v1alpha1_resource_policy_rule import V1alpha1ResourcePolicyRuleDict
from kubernetes_typed.client.models.flowcontrol_v1alpha1_subject import FlowcontrolV1alpha1SubjectDict

V1alpha1PolicyRulesWithSubjectsDict = TypedDict(
    "V1alpha1PolicyRulesWithSubjectsDict",
    {
        "nonResourceRules": List[V1alpha1NonResourcePolicyRuleDict],
        "resourceRules": List[V1alpha1ResourcePolicyRuleDict],
        "subjects": List[FlowcontrolV1alpha1SubjectDict],
    },
    total=False,
)
