# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PodPresetDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1alpha1PodPresetSpecDict

V1alpha1PodPresetDict = TypedDict(
    "V1alpha1PodPresetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1alpha1PodPresetSpecDict,
    },
    total=False,
)
