# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1NonResourcePolicyRuleDict generated type."""
from typing import TypedDict, List

V1alpha1NonResourcePolicyRuleDict = TypedDict(
    "V1alpha1NonResourcePolicyRuleDict",
    {
        "nonResourceURLs": List[str],
        "verbs": List[str],
    },
    total=False,
)
