# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PodPresetSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_env_var import V1EnvVarDict
from kubernetes_typed.client.models.v1_env_from_source import V1EnvFromSourceDict
from kubernetes_typed.client.models.v1_label_selector import V1LabelSelectorDict
from kubernetes_typed.client.models.v1_volume_mount import V1VolumeMountDict
from kubernetes_typed.client.models.v1_volume import V1VolumeDict

V1alpha1PodPresetSpecDict = TypedDict(
    "V1alpha1PodPresetSpecDict",
    {
        "env": List[V1EnvVarDict],
        "envFrom": List[V1EnvFromSourceDict],
        "selector": V1LabelSelectorDict,
        "volumeMounts": List[V1VolumeMountDict],
        "volumes": List[V1VolumeDict],
    },
    total=False,
)
