# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PriorityLevelConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1alpha1PriorityLevelConfigurationDict

V1alpha1PriorityLevelConfigurationListDict = TypedDict(
    "V1alpha1PriorityLevelConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1PriorityLevelConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
