# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PriorityLevelConfigurationSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1alpha1LimitedPriorityLevelConfigurationDict

V1alpha1PriorityLevelConfigurationSpecDict = TypedDict(
    "V1alpha1PriorityLevelConfigurationSpecDict",
    {
        "limited": V1alpha1LimitedPriorityLevelConfigurationDict,
        "type": str,
    },
    total=False,
)
