# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1ServiceAccountSubjectDict generated type."""
from typing import TypedDict

V1alpha1ServiceAccountSubjectDict = TypedDict(
    "V1alpha1ServiceAccountSubjectDict",
    {
        "name": str,
        "namespace": str,
    },
    total=False,
)
