# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1LimitResponseDict generated type."""
from typing import TypedDict

from .v1alpha1_queuing_configuration import V1alpha1QueuingConfigurationDict

V1alpha1LimitResponseDict = TypedDict(
    "V1alpha1LimitResponseDict",
    {
        "queuing": V1alpha1QueuingConfigurationDict,
        "type": str,
    },
    total=False,
)
