# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1PolicyRuleDict generated type."""
from typing import TypedDict, List

V1alpha1PolicyRuleDict = TypedDict(
    "V1alpha1PolicyRuleDict",
    {
        "apiGroups": List[str],
        "nonResourceURLs": List[str],
        "resourceNames": List[str],
        "resources": List[str],
        "verbs": List[str],
    },
    total=False,
)
