# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1alpha1AuditSinkListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1alpha1_audit_sink import V1alpha1AuditSinkDict

V1alpha1AuditSinkListDict = TypedDict(
    "V1alpha1AuditSinkListDict",
    {
        "apiVersion": str,
        "items": List[V1alpha1AuditSinkDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
