# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeAttachmentListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_volume_attachment import V1beta1VolumeAttachmentDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1VolumeAttachmentListDict = TypedDict(
    "V1beta1VolumeAttachmentListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1VolumeAttachmentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
