# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ClusterRoleListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_cluster_role import V1beta1ClusterRoleDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1ClusterRoleListDict = TypedDict(
    "V1beta1ClusterRoleListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1ClusterRoleDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
