# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CSIDriverListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_csi_driver import V1beta1CSIDriverDict

V1beta1CSIDriverListDict = TypedDict(
    "V1beta1CSIDriverListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1CSIDriverDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
