# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EventSeriesDict generated type."""
import datetime
from typing import TypedDict

V1beta1EventSeriesDict = TypedDict(
    "V1beta1EventSeriesDict",
    {
        "count": int,
        "lastObservedTime": datetime.datetime,
        "state": str,
    },
    total=False,
)
