# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1beta1CustomResourceColumnDefinitionDict = TypedDict(
    "V1beta1CustomResourceColumnDefinitionDict",
    {
        "JSONPath": str,
        "description": str,
        "format": str,
        "name": str,
        "priority": int,
        "type": str,
    },
    total=False,
)