# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RoleListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_role import V1beta1RoleDict

V1beta1RoleListDict = TypedDict(
    "V1beta1RoleListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1RoleDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
