# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta1ExternalDocumentationDict = TypedDict(
    "V1beta1ExternalDocumentationDict",
    {
        "description": str,
        "url": str,
    },
    total=False,
)
