# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta2DeploymentDict

V1beta2DeploymentListDict = TypedDict(
    "V1beta2DeploymentListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2DeploymentDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
