# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CSIDriverDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_csi_driver_spec import V1beta1CSIDriverSpecDict

V1beta1CSIDriverDict = TypedDict(
    "V1beta1CSIDriverDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CSIDriverSpecDict,
    },
    total=False,
)
