# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CSINodeDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1CSINodeSpecDict

V1beta1CSINodeDict = TypedDict(
    "V1beta1CSINodeDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CSINodeSpecDict,
    },
    total=False,
)
