# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PodDisruptionBudgetListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_pod_disruption_budget import V1beta1PodDisruptionBudgetDict

V1beta1PodDisruptionBudgetListDict = TypedDict(
    "V1beta1PodDisruptionBudgetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1PodDisruptionBudgetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
