# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1beta1NonResourceAttributesDict = TypedDict(
    "V1beta1NonResourceAttributesDict",
    {
        "path": str,
        "verb": str,
    },
    total=False,
)