# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1FSGroupStrategyOptionsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1IDRangeDict

V1beta1FSGroupStrategyOptionsDict = TypedDict(
    "V1beta1FSGroupStrategyOptionsDict",
    {
        "ranges": List[V1beta1IDRangeDict],
        "rule": str,
    },
    total=False,
)
