# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1beta1NetworkPolicyPeerDict, V1beta1NetworkPolicyPortDict

V1beta1NetworkPolicyIngressRuleDict = TypedDict(
    "V1beta1NetworkPolicyIngressRuleDict",
    {
        "from": List[V1beta1NetworkPolicyPeerDict],
        "ports": List[V1beta1NetworkPolicyPortDict],
    },
    total=False,
)