# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1SelfSubjectRulesReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1SelfSubjectRulesReviewSpecDict, V1beta1SubjectRulesReviewStatusDict

V1beta1SelfSubjectRulesReviewDict = TypedDict(
    "V1beta1SelfSubjectRulesReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1SelfSubjectRulesReviewSpecDict,
        "status": V1beta1SubjectRulesReviewStatusDict,
    },
    total=False,
)
