# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1SelfSubjectRulesReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_self_subject_rules_review_spec import V1beta1SelfSubjectRulesReviewSpecDict
from kubernetes_typed.client.models.v1beta1_subject_rules_review_status import V1beta1SubjectRulesReviewStatusDict

V1beta1SelfSubjectRulesReviewDict = TypedDict(
    "V1beta1SelfSubjectRulesReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1SelfSubjectRulesReviewSpecDict,
        "status": V1beta1SubjectRulesReviewStatusDict,
    },
    total=False,
)
