# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CertificateSigningRequestListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_certificate_signing_request import V1beta1CertificateSigningRequestDict

V1beta1CertificateSigningRequestListDict = TypedDict(
    "V1beta1CertificateSigningRequestListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1CertificateSigningRequestDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
