# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1MutatingWebhookConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1MutatingWebhookConfigurationDict

V1beta1MutatingWebhookConfigurationListDict = TypedDict(
    "V1beta1MutatingWebhookConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1MutatingWebhookConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
