# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EndpointConditionsDict generated type."""
from typing import TypedDict

V1beta1EndpointConditionsDict = TypedDict(
    "V1beta1EndpointConditionsDict",
    {
        "ready": bool,
    },
    total=False,
)
