# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1DaemonSetSpecDict, V1beta1DaemonSetStatusDict

V1beta1DaemonSetDict = TypedDict(
    "V1beta1DaemonSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1DaemonSetSpecDict,
        "status": V1beta1DaemonSetStatusDict,
    },
    total=False,
)
