# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1LabelSelectorDict, V1PodTemplateSpecDict, V1beta2DaemonSetUpdateStrategyDict

V1beta2DaemonSetSpecDict = TypedDict(
    "V1beta2DaemonSetSpecDict",
    {
        "minReadySeconds": int,
        "revisionHistoryLimit": int,
        "selector": V1LabelSelectorDict,
        "template": V1PodTemplateSpecDict,
        "updateStrategy": V1beta2DaemonSetUpdateStrategyDict,
    },
    total=False,
)