# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1ObjectMetaDict, V1beta1CronJobSpecDict, V1beta1CronJobStatusDict

V1beta1CronJobDict = TypedDict(
    "V1beta1CronJobDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CronJobSpecDict,
        "status": V1beta1CronJobStatusDict,
    },
    total=False,
)