# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IngressClassListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_ingress_class import V1beta1IngressClassDict

V1beta1IngressClassListDict = TypedDict(
    "V1beta1IngressClassListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1IngressClassDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
