# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1ListMetaDict, V1beta2ReplicaSetDict

V1beta2ReplicaSetListDict = TypedDict(
    "V1beta2ReplicaSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2ReplicaSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)