# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1SELinuxStrategyOptionsDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1SELinuxOptionsDict

V1beta1SELinuxStrategyOptionsDict = TypedDict(
    "V1beta1SELinuxStrategyOptionsDict",
    {
        "rule": str,
        "seLinuxOptions": V1SELinuxOptionsDict,
    },
    total=False,
)
