# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionNamesDict generated type."""
from typing import TypedDict, List

V1beta1CustomResourceDefinitionNamesDict = TypedDict(
    "V1beta1CustomResourceDefinitionNamesDict",
    {
        "categories": List[str],
        "kind": str,
        "listKind": str,
        "plural": str,
        "shortNames": List[str],
        "singular": str,
    },
    total=False,
)
