# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RoleBindingListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_role_binding import V1beta1RoleBindingDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1RoleBindingListDict = TypedDict(
    "V1beta1RoleBindingListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1RoleBindingDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
