# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceValidationDict generated type."""
from typing import TypedDict

from .v1beta1_json_schema_props import V1beta1JSONSchemaPropsDict

V1beta1CustomResourceValidationDict = TypedDict(
    "V1beta1CustomResourceValidationDict",
    {
        "openAPIV3Schema": V1beta1JSONSchemaPropsDict,
    },
    total=False,
)
