# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1APIServiceStatusDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1APIServiceConditionDict

V1beta1APIServiceStatusDict = TypedDict(
    "V1beta1APIServiceStatusDict",
    {
        "conditions": List[V1beta1APIServiceConditionDict],
    },
    total=False,
)
