# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta1RoleRefDict = TypedDict(
    "V1beta1RoleRefDict",
    {
        "apiGroup": str,
        "kind": str,
        "name": str,
    },
    total=False,
)
