# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CertificateSigningRequestDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_certificate_signing_request_spec import V1beta1CertificateSigningRequestSpecDict
from .v1beta1_certificate_signing_request_status import V1beta1CertificateSigningRequestStatusDict

V1beta1CertificateSigningRequestDict = TypedDict(
    "V1beta1CertificateSigningRequestDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CertificateSigningRequestSpecDict,
        "status": V1beta1CertificateSigningRequestStatusDict,
    },
    total=False,
)
