# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1beta1SubjectAccessReviewStatusDict = TypedDict(
    "V1beta1SubjectAccessReviewStatusDict",
    {
        "allowed": bool,
        "denied": bool,
        "evaluationError": str,
        "reason": str,
    },
    total=False,
)