# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RuntimeClassListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1RuntimeClassDict

V1beta1RuntimeClassListDict = TypedDict(
    "V1beta1RuntimeClassListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1RuntimeClassDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
