# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EndpointDict generated type."""
from typing import TypedDict, Dict, List

from .v1_object_reference import V1ObjectReferenceDict
from .v1beta1_endpoint_conditions import V1beta1EndpointConditionsDict

V1beta1EndpointDict = TypedDict(
    "V1beta1EndpointDict",
    {
        "addresses": List[str],
        "conditions": V1beta1EndpointConditionsDict,
        "hostname": str,
        "targetRef": V1ObjectReferenceDict,
        "topology": Dict[str, str],
    },
    total=False,
)
