# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingWebhookDict generated type."""
from typing import TypedDict, List

from .admissionregistration_v1beta1_webhook_client_config import AdmissionregistrationV1beta1WebhookClientConfigDict
from .v1_label_selector import V1LabelSelectorDict
from .v1beta1_rule_with_operations import V1beta1RuleWithOperationsDict

V1beta1ValidatingWebhookDict = TypedDict(
    "V1beta1ValidatingWebhookDict",
    {
        "admissionReviewVersions": List[str],
        "clientConfig": AdmissionregistrationV1beta1WebhookClientConfigDict,
        "failurePolicy": str,
        "matchPolicy": str,
        "name": str,
        "namespaceSelector": V1LabelSelectorDict,
        "objectSelector": V1LabelSelectorDict,
        "rules": List[V1beta1RuleWithOperationsDict],
        "sideEffects": str,
        "timeoutSeconds": int,
    },
    total=False,
)
