# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict, V1PodTemplateSpecDict

V1beta2ReplicaSetSpecDict = TypedDict(
    "V1beta2ReplicaSetSpecDict",
    {
        "minReadySeconds": int,
        "replicas": int,
        "selector": V1LabelSelectorDict,
        "template": V1PodTemplateSpecDict,
    },
    total=False,
)
