# Code generated by `typeddictgen`. DO NOT EDIT.
import datetime
from typing import TypedDict, Dict

V1beta1PodDisruptionBudgetStatusDict = TypedDict(
    "V1beta1PodDisruptionBudgetStatusDict",
    {
        "currentHealthy": int,
        "desiredHealthy": int,
        "disruptedPods": Dict[str, datetime.datetime],
        "disruptionsAllowed": int,
        "expectedPods": int,
        "observedGeneration": int,
    },
    total=False,
)
