# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta1RollingUpdateDaemonSetDict = TypedDict(
    "V1beta1RollingUpdateDaemonSetDict",
    {
        "maxUnavailable": object,
    },
    total=False,
)
