# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1beta1DaemonSetConditionDict

V1beta1DaemonSetStatusDict = TypedDict(
    "V1beta1DaemonSetStatusDict",
    {
        "collisionCount": int,
        "conditions": List[V1beta1DaemonSetConditionDict],
        "currentNumberScheduled": int,
        "desiredNumberScheduled": int,
        "numberAvailable": int,
        "numberMisscheduled": int,
        "numberReady": int,
        "numberUnavailable": int,
        "observedGeneration": int,
        "updatedNumberScheduled": int,
    },
    total=False,
)