# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeAttachmentDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_volume_attachment_spec import V1beta1VolumeAttachmentSpecDict
from kubernetes_typed.client.models.v1beta1_volume_attachment_status import V1beta1VolumeAttachmentStatusDict

V1beta1VolumeAttachmentDict = TypedDict(
    "V1beta1VolumeAttachmentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1VolumeAttachmentSpecDict,
        "status": V1beta1VolumeAttachmentStatusDict,
    },
    total=False,
)
