# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1APIServiceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1APIServiceSpecDict, V1beta1APIServiceStatusDict

V1beta1APIServiceDict = TypedDict(
    "V1beta1APIServiceDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1APIServiceSpecDict,
        "status": V1beta1APIServiceStatusDict,
    },
    total=False,
)
