# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CronJobSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1JobTemplateSpecDict

V1beta1CronJobSpecDict = TypedDict(
    "V1beta1CronJobSpecDict",
    {
        "concurrencyPolicy": str,
        "failedJobsHistoryLimit": int,
        "jobTemplate": V1beta1JobTemplateSpecDict,
        "schedule": str,
        "startingDeadlineSeconds": int,
        "successfulJobsHistoryLimit": int,
        "suspend": bool,
    },
    total=False,
)
