# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

V1beta1IPBlockDict = TypedDict(
    "V1beta1IPBlockDict",
    {
        "cidr": str,
        "except": List[str],
    },
    total=False,
)
