# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_custom_resource_column_definition import V1beta1CustomResourceColumnDefinitionDict
from kubernetes_typed.client.models.v1beta1_custom_resource_conversion import V1beta1CustomResourceConversionDict
from kubernetes_typed.client.models.v1beta1_custom_resource_definition_names import V1beta1CustomResourceDefinitionNamesDict
from kubernetes_typed.client.models.v1beta1_custom_resource_subresources import V1beta1CustomResourceSubresourcesDict
from kubernetes_typed.client.models.v1beta1_custom_resource_validation import V1beta1CustomResourceValidationDict
from kubernetes_typed.client.models.v1beta1_custom_resource_definition_version import V1beta1CustomResourceDefinitionVersionDict

V1beta1CustomResourceDefinitionSpecDict = TypedDict(
    "V1beta1CustomResourceDefinitionSpecDict",
    {
        "additionalPrinterColumns": List[V1beta1CustomResourceColumnDefinitionDict],
        "conversion": V1beta1CustomResourceConversionDict,
        "group": str,
        "names": V1beta1CustomResourceDefinitionNamesDict,
        "preserveUnknownFields": bool,
        "scope": str,
        "subresources": V1beta1CustomResourceSubresourcesDict,
        "validation": V1beta1CustomResourceValidationDict,
        "version": str,
        "versions": List[V1beta1CustomResourceDefinitionVersionDict],
    },
    total=False,
)
