# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_custom_resource_definition import V1beta1CustomResourceDefinitionDict

V1beta1CustomResourceDefinitionListDict = TypedDict(
    "V1beta1CustomResourceDefinitionListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1CustomResourceDefinitionDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
