# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1LocalSubjectAccessReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_subject_access_review_spec import V1beta1SubjectAccessReviewSpecDict
from kubernetes_typed.client.models.v1beta1_subject_access_review_status import V1beta1SubjectAccessReviewStatusDict

V1beta1LocalSubjectAccessReviewDict = TypedDict(
    "V1beta1LocalSubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1SubjectAccessReviewSpecDict,
        "status": V1beta1SubjectAccessReviewStatusDict,
    },
    total=False,
)
