# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IngressClassDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_ingress_class_spec import V1beta1IngressClassSpecDict

V1beta1IngressClassDict = TypedDict(
    "V1beta1IngressClassDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1IngressClassSpecDict,
    },
    total=False,
)
