# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1AllowedCSIDriverDict generated type."""
from typing import TypedDict

V1beta1AllowedCSIDriverDict = TypedDict(
    "V1beta1AllowedCSIDriverDict",
    {
        "name": str,
    },
    total=False,
)
