# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionVersionDict generated type."""
from typing import TypedDict, List

from .v1beta1_custom_resource_column_definition import V1beta1CustomResourceColumnDefinitionDict
from .v1beta1_custom_resource_subresources import V1beta1CustomResourceSubresourcesDict
from .v1beta1_custom_resource_validation import V1beta1CustomResourceValidationDict

V1beta1CustomResourceDefinitionVersionDict = TypedDict(
    "V1beta1CustomResourceDefinitionVersionDict",
    {
        "additionalPrinterColumns": List[V1beta1CustomResourceColumnDefinitionDict],
        "name": str,
        "schema": V1beta1CustomResourceValidationDict,
        "served": bool,
        "storage": bool,
        "subresources": V1beta1CustomResourceSubresourcesDict,
    },
    total=False,
)
