# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1NonResourceAttributesDict generated type."""
from typing import TypedDict

V1beta1NonResourceAttributesDict = TypedDict(
    "V1beta1NonResourceAttributesDict",
    {
        "path": str,
        "verb": str,
    },
    total=False,
)
