# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1ObjectMetaDict, V1beta1NetworkPolicySpecDict

V1beta1NetworkPolicyDict = TypedDict(
    "V1beta1NetworkPolicyDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1NetworkPolicySpecDict,
    },
    total=False,
)