# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_custom_resource_definition_spec import V1beta1CustomResourceDefinitionSpecDict
from .v1beta1_custom_resource_definition_status import V1beta1CustomResourceDefinitionStatusDict

V1beta1CustomResourceDefinitionDict = TypedDict(
    "V1beta1CustomResourceDefinitionDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CustomResourceDefinitionSpecDict,
        "status": V1beta1CustomResourceDefinitionStatusDict,
    },
    total=False,
)
