# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1APIServiceSpecDict generated type."""
from typing import TypedDict

from .apiregistration_v1beta1_service_reference import ApiregistrationV1beta1ServiceReferenceDict

V1beta1APIServiceSpecDict = TypedDict(
    "V1beta1APIServiceSpecDict",
    {
        "caBundle": str,
        "group": str,
        "groupPriorityMinimum": int,
        "insecureSkipTLSVerify": bool,
        "service": ApiregistrationV1beta1ServiceReferenceDict,
        "version": str,
        "versionPriority": int,
    },
    total=False,
)
