# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceColumnDefinitionDict generated type."""
from typing import TypedDict

V1beta1CustomResourceColumnDefinitionDict = TypedDict(
    "V1beta1CustomResourceColumnDefinitionDict",
    {
        "JSONPath": str,
        "description": str,
        "format": str,
        "name": str,
        "priority": int,
        "type": str,
    },
    total=False,
)
