# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1beta2DeploymentConditionDict

V1beta2DeploymentStatusDict = TypedDict(
    "V1beta2DeploymentStatusDict",
    {
        "availableReplicas": int,
        "collisionCount": int,
        "conditions": List[V1beta2DeploymentConditionDict],
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
        "unavailableReplicas": int,
        "updatedReplicas": int,
    },
    total=False,
)