# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta1RollingUpdateStatefulSetStrategyDict = TypedDict(
    "V1beta1RollingUpdateStatefulSetStrategyDict",
    {
        "partition": int,
    },
    total=False,
)
