# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RuntimeClassDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_overhead import V1beta1OverheadDict
from .v1beta1_scheduling import V1beta1SchedulingDict

V1beta1RuntimeClassDict = TypedDict(
    "V1beta1RuntimeClassDict",
    {
        "apiVersion": str,
        "handler": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "overhead": V1beta1OverheadDict,
        "scheduling": V1beta1SchedulingDict,
    },
    total=False,
)
