# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1SelfSubjectAccessReviewSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1NonResourceAttributesDict, V1beta1ResourceAttributesDict

V1beta1SelfSubjectAccessReviewSpecDict = TypedDict(
    "V1beta1SelfSubjectAccessReviewSpecDict",
    {
        "nonResourceAttributes": V1beta1NonResourceAttributesDict,
        "resourceAttributes": V1beta1ResourceAttributesDict,
    },
    total=False,
)
