# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1beta2ReplicaSetConditionDict

V1beta2ReplicaSetStatusDict = TypedDict(
    "V1beta2ReplicaSetStatusDict",
    {
        "availableReplicas": int,
        "conditions": List[V1beta2ReplicaSetConditionDict],
        "fullyLabeledReplicas": int,
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
    },
    total=False,
)