# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1SelfSubjectAccessReviewDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_self_subject_access_review_spec import V1beta1SelfSubjectAccessReviewSpecDict
from .v1beta1_subject_access_review_status import V1beta1SubjectAccessReviewStatusDict

V1beta1SelfSubjectAccessReviewDict = TypedDict(
    "V1beta1SelfSubjectAccessReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1SelfSubjectAccessReviewSpecDict,
        "status": V1beta1SubjectAccessReviewStatusDict,
    },
    total=False,
)
