# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1ObjectMetaDict, V1beta2DeploymentSpecDict, V1beta2DeploymentStatusDict

V1beta2DeploymentDict = TypedDict(
    "V1beta2DeploymentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta2DeploymentSpecDict,
        "status": V1beta2DeploymentStatusDict,
    },
    total=False,
)