# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1beta2RollingUpdateStatefulSetStrategyDict

V1beta2StatefulSetUpdateStrategyDict = TypedDict(
    "V1beta2StatefulSetUpdateStrategyDict",
    {
        "rollingUpdate": V1beta2RollingUpdateStatefulSetStrategyDict,
        "type": str,
    },
    total=False,
)