# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1AllowedFlexVolumeDict generated type."""
from typing import TypedDict

V1beta1AllowedFlexVolumeDict = TypedDict(
    "V1beta1AllowedFlexVolumeDict",
    {
        "driver": str,
    },
    total=False,
)
