# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RunAsUserStrategyOptionsDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_id_range import V1beta1IDRangeDict

V1beta1RunAsUserStrategyOptionsDict = TypedDict(
    "V1beta1RunAsUserStrategyOptionsDict",
    {
        "ranges": List[V1beta1IDRangeDict],
        "rule": str,
    },
    total=False,
)
