# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1HostPortRangeDict generated type."""
from typing import TypedDict

V1beta1HostPortRangeDict = TypedDict(
    "V1beta1HostPortRangeDict",
    {
        "max": int,
        "min": int,
    },
    total=False,
)
