# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1LeaseDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_lease_spec import V1beta1LeaseSpecDict

V1beta1LeaseDict = TypedDict(
    "V1beta1LeaseDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1LeaseSpecDict,
    },
    total=False,
)
