# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceValidationDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1beta1JSONSchemaPropsDict

V1beta1CustomResourceValidationDict = TypedDict(
    "V1beta1CustomResourceValidationDict",
    {
        "openAPIV3Schema": V1beta1JSONSchemaPropsDict,
    },
    total=False,
)
