# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1ListMetaDict, V1beta1DaemonSetDict

V1beta1DaemonSetListDict = TypedDict(
    "V1beta1DaemonSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1DaemonSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)