# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1TokenReviewSpecDict generated type."""
from typing import TypedDict, List

V1beta1TokenReviewSpecDict = TypedDict(
    "V1beta1TokenReviewSpecDict",
    {
        "audiences": List[str],
        "token": str,
    },
    total=False,
)
