# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1NetworkPolicyPeerDict, V1beta1NetworkPolicyPortDict

V1beta1NetworkPolicyEgressRuleDict = TypedDict(
    "V1beta1NetworkPolicyEgressRuleDict",
    {
        "ports": List[V1beta1NetworkPolicyPortDict],
        "to": List[V1beta1NetworkPolicyPeerDict],
    },
    total=False,
)
