# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1ValidatingWebhookConfigurationListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_validating_webhook_configuration import V1beta1ValidatingWebhookConfigurationDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1ValidatingWebhookConfigurationListDict = TypedDict(
    "V1beta1ValidatingWebhookConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1ValidatingWebhookConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
