# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeNodeResourcesDict generated type."""
from typing import TypedDict

V1beta1VolumeNodeResourcesDict = TypedDict(
    "V1beta1VolumeNodeResourcesDict",
    {
        "count": int,
    },
    total=False,
)
