# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1AllowedHostPathDict generated type."""
from typing import TypedDict

V1beta1AllowedHostPathDict = TypedDict(
    "V1beta1AllowedHostPathDict",
    {
        "pathPrefix": str,
        "readOnly": bool,
    },
    total=False,
)
