# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1ListMetaDict, V1beta2StatefulSetDict

V1beta2StatefulSetListDict = TypedDict(
    "V1beta2StatefulSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2StatefulSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)