# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1LabelSelectorDict, V1PodTemplateSpecDict, V1beta2DeploymentStrategyDict

V1beta2DeploymentSpecDict = TypedDict(
    "V1beta2DeploymentSpecDict",
    {
        "minReadySeconds": int,
        "paused": bool,
        "progressDeadlineSeconds": int,
        "replicas": int,
        "revisionHistoryLimit": int,
        "selector": V1LabelSelectorDict,
        "strategy": V1beta2DeploymentStrategyDict,
        "template": V1PodTemplateSpecDict,
    },
    total=False,
)