# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EndpointPortDict generated type."""
from typing import TypedDict

V1beta1EndpointPortDict = TypedDict(
    "V1beta1EndpointPortDict",
    {
        "appProtocol": str,
        "name": str,
        "port": int,
        "protocol": str,
    },
    total=False,
)
