# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1MutatingWebhookConfigurationDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_mutating_webhook import V1beta1MutatingWebhookDict

V1beta1MutatingWebhookConfigurationDict = TypedDict(
    "V1beta1MutatingWebhookConfigurationDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "webhooks": List[V1beta1MutatingWebhookDict],
    },
    total=False,
)
