# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PodDisruptionBudgetListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1PodDisruptionBudgetDict

V1beta1PodDisruptionBudgetListDict = TypedDict(
    "V1beta1PodDisruptionBudgetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1PodDisruptionBudgetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
