# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CronJobDict generated type."""
from typing import TypedDict

from .v1_object_meta import V1ObjectMetaDict
from .v1beta1_cron_job_spec import V1beta1CronJobSpecDict
from .v1beta1_cron_job_status import V1beta1CronJobStatusDict

V1beta1CronJobDict = TypedDict(
    "V1beta1CronJobDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1CronJobSpecDict,
        "status": V1beta1CronJobStatusDict,
    },
    total=False,
)
