# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CertificateSigningRequestConditionDict generated type."""
import datetime
from typing import TypedDict

V1beta1CertificateSigningRequestConditionDict = TypedDict(
    "V1beta1CertificateSigningRequestConditionDict",
    {
        "lastUpdateTime": datetime.datetime,
        "message": str,
        "reason": str,
        "type": str,
    },
    total=False,
)
