# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta2RollingUpdateDeploymentDict = TypedDict(
    "V1beta2RollingUpdateDeploymentDict",
    {
        "maxSurge": object,
        "maxUnavailable": object,
    },
    total=False,
)
