# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PodSecurityPolicySpecDict generated type."""
from typing import TypedDict, List

from .v1beta1_allowed_csi_driver import V1beta1AllowedCSIDriverDict
from .v1beta1_allowed_flex_volume import V1beta1AllowedFlexVolumeDict
from .v1beta1_allowed_host_path import V1beta1AllowedHostPathDict
from .v1beta1_fs_group_strategy_options import V1beta1FSGroupStrategyOptionsDict
from .v1beta1_host_port_range import V1beta1HostPortRangeDict
from .v1beta1_run_as_group_strategy_options import V1beta1RunAsGroupStrategyOptionsDict
from .v1beta1_run_as_user_strategy_options import V1beta1RunAsUserStrategyOptionsDict
from .v1beta1_runtime_class_strategy_options import V1beta1RuntimeClassStrategyOptionsDict
from .v1beta1_se_linux_strategy_options import V1beta1SELinuxStrategyOptionsDict
from .v1beta1_supplemental_groups_strategy_options import V1beta1SupplementalGroupsStrategyOptionsDict

V1beta1PodSecurityPolicySpecDict = TypedDict(
    "V1beta1PodSecurityPolicySpecDict",
    {
        "allowPrivilegeEscalation": bool,
        "allowedCSIDrivers": List[V1beta1AllowedCSIDriverDict],
        "allowedCapabilities": List[str],
        "allowedFlexVolumes": List[V1beta1AllowedFlexVolumeDict],
        "allowedHostPaths": List[V1beta1AllowedHostPathDict],
        "allowedProcMountTypes": List[str],
        "allowedUnsafeSysctls": List[str],
        "defaultAddCapabilities": List[str],
        "defaultAllowPrivilegeEscalation": bool,
        "forbiddenSysctls": List[str],
        "fsGroup": V1beta1FSGroupStrategyOptionsDict,
        "hostIPC": bool,
        "hostNetwork": bool,
        "hostPID": bool,
        "hostPorts": List[V1beta1HostPortRangeDict],
        "privileged": bool,
        "readOnlyRootFilesystem": bool,
        "requiredDropCapabilities": List[str],
        "runAsGroup": V1beta1RunAsGroupStrategyOptionsDict,
        "runAsUser": V1beta1RunAsUserStrategyOptionsDict,
        "runtimeClass": V1beta1RuntimeClassStrategyOptionsDict,
        "seLinux": V1beta1SELinuxStrategyOptionsDict,
        "supplementalGroups": V1beta1SupplementalGroupsStrategyOptionsDict,
        "volumes": List[str],
    },
    total=False,
)
