# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1beta2RollingUpdateDaemonSetDict

V1beta2DaemonSetUpdateStrategyDict = TypedDict(
    "V1beta2DaemonSetUpdateStrategyDict",
    {
        "rollingUpdate": V1beta2RollingUpdateDaemonSetDict,
        "type": str,
    },
    total=False,
)
