# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RuntimeClassStrategyOptionsDict generated type."""
from typing import TypedDict, List

V1beta1RuntimeClassStrategyOptionsDict = TypedDict(
    "V1beta1RuntimeClassStrategyOptionsDict",
    {
        "allowedRuntimeClassNames": List[str],
        "defaultRuntimeClassName": str,
    },
    total=False,
)
