# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta2StatefulSetSpecDict, V1beta2StatefulSetStatusDict

V1beta2StatefulSetDict = TypedDict(
    "V1beta2StatefulSetDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta2StatefulSetSpecDict,
        "status": V1beta2StatefulSetStatusDict,
    },
    total=False,
)
