# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta2DaemonSetDict

V1beta2DaemonSetListDict = TypedDict(
    "V1beta2DaemonSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta2DaemonSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
