# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CronJobListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_cron_job import V1beta1CronJobDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1CronJobListDict = TypedDict(
    "V1beta1CronJobListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1CronJobDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
