# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceSubresourceScaleDict generated type."""
from typing import TypedDict

V1beta1CustomResourceSubresourceScaleDict = TypedDict(
    "V1beta1CustomResourceSubresourceScaleDict",
    {
        "labelSelectorPath": str,
        "specReplicasPath": str,
        "statusReplicasPath": str,
    },
    total=False,
)
