# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IDRangeDict generated type."""
from typing import TypedDict

V1beta1IDRangeDict = TypedDict(
    "V1beta1IDRangeDict",
    {
        "max": int,
        "min": int,
    },
    total=False,
)
