# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1IngressClassDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1IngressClassSpecDict

V1beta1IngressClassDict = TypedDict(
    "V1beta1IngressClassDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1IngressClassSpecDict,
    },
    total=False,
)
