# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List


from kubernetes_typed.client import V1beta2StatefulSetConditionDict

V1beta2StatefulSetStatusDict = TypedDict(
    "V1beta2StatefulSetStatusDict",
    {
        "collisionCount": int,
        "conditions": List[V1beta2StatefulSetConditionDict],
        "currentReplicas": int,
        "currentRevision": str,
        "observedGeneration": int,
        "readyReplicas": int,
        "replicas": int,
        "updateRevision": str,
        "updatedReplicas": int,
    },
    total=False,
)