# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1MutatingWebhookConfigurationListDict generated type."""
from typing import TypedDict, List

from .v1_list_meta import V1ListMetaDict
from .v1beta1_mutating_webhook_configuration import V1beta1MutatingWebhookConfigurationDict

V1beta1MutatingWebhookConfigurationListDict = TypedDict(
    "V1beta1MutatingWebhookConfigurationListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1MutatingWebhookConfigurationDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
