# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V1beta1NetworkPolicyPortDict = TypedDict(
    "V1beta1NetworkPolicyPortDict",
    {
        "port": object,
        "protocol": str,
    },
    total=False,
)
