# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1CustomResourceDefinitionVersionDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1beta1CustomResourceColumnDefinitionDict, V1beta1CustomResourceSubresourcesDict, V1beta1CustomResourceValidationDict

V1beta1CustomResourceDefinitionVersionDict = TypedDict(
    "V1beta1CustomResourceDefinitionVersionDict",
    {
        "additionalPrinterColumns": List[V1beta1CustomResourceColumnDefinitionDict],
        "name": str,
        "schema": V1beta1CustomResourceValidationDict,
        "served": bool,
        "storage": bool,
        "subresources": V1beta1CustomResourceSubresourcesDict,
    },
    total=False,
)
