# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1TokenReviewDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v1beta1_token_review_spec import V1beta1TokenReviewSpecDict
from kubernetes_typed.client.models.v1beta1_token_review_status import V1beta1TokenReviewStatusDict

V1beta1TokenReviewDict = TypedDict(
    "V1beta1TokenReviewDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1TokenReviewSpecDict,
        "status": V1beta1TokenReviewStatusDict,
    },
    total=False,
)
