# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1RoleBindingDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1RoleRefDict, V1beta1SubjectDict

V1beta1RoleBindingDict = TypedDict(
    "V1beta1RoleBindingDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "roleRef": V1beta1RoleRefDict,
        "subjects": List[V1beta1SubjectDict],
    },
    total=False,
)
