# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1PodSecurityPolicySpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import (
    V1beta1AllowedCSIDriverDict,
    V1beta1AllowedFlexVolumeDict,
    V1beta1AllowedHostPathDict,
    V1beta1FSGroupStrategyOptionsDict,
    V1beta1HostPortRangeDict,
    V1beta1RunAsGroupStrategyOptionsDict,
    V1beta1RunAsUserStrategyOptionsDict,
    V1beta1RuntimeClassStrategyOptionsDict,
    V1beta1SELinuxStrategyOptionsDict,
    V1beta1SupplementalGroupsStrategyOptionsDict,
)

V1beta1PodSecurityPolicySpecDict = TypedDict(
    "V1beta1PodSecurityPolicySpecDict",
    {
        "allowPrivilegeEscalation": bool,
        "allowedCSIDrivers": List[V1beta1AllowedCSIDriverDict],
        "allowedCapabilities": List[str],
        "allowedFlexVolumes": List[V1beta1AllowedFlexVolumeDict],
        "allowedHostPaths": List[V1beta1AllowedHostPathDict],
        "allowedProcMountTypes": List[str],
        "allowedUnsafeSysctls": List[str],
        "defaultAddCapabilities": List[str],
        "defaultAllowPrivilegeEscalation": bool,
        "forbiddenSysctls": List[str],
        "fsGroup": V1beta1FSGroupStrategyOptionsDict,
        "hostIPC": bool,
        "hostNetwork": bool,
        "hostPID": bool,
        "hostPorts": List[V1beta1HostPortRangeDict],
        "privileged": bool,
        "readOnlyRootFilesystem": bool,
        "requiredDropCapabilities": List[str],
        "runAsGroup": V1beta1RunAsGroupStrategyOptionsDict,
        "runAsUser": V1beta1RunAsUserStrategyOptionsDict,
        "runtimeClass": V1beta1RuntimeClassStrategyOptionsDict,
        "seLinux": V1beta1SELinuxStrategyOptionsDict,
        "supplementalGroups": V1beta1SupplementalGroupsStrategyOptionsDict,
        "volumes": List[str],
    },
    total=False,
)
