# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1StorageClassListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v1beta1_storage_class import V1beta1StorageClassDict
from kubernetes_typed.client.models.v1_list_meta import V1ListMetaDict

V1beta1StorageClassListDict = TypedDict(
    "V1beta1StorageClassListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1StorageClassDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
