# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1EventDict generated type."""
import datetime
from typing import TypedDict

from .v1_event_source import V1EventSourceDict
from .v1_object_meta import V1ObjectMetaDict
from .v1_object_reference import V1ObjectReferenceDict
from .v1beta1_event_series import V1beta1EventSeriesDict

V1beta1EventDict = TypedDict(
    "V1beta1EventDict",
    {
        "action": str,
        "apiVersion": str,
        "deprecatedCount": int,
        "deprecatedFirstTimestamp": datetime.datetime,
        "deprecatedLastTimestamp": datetime.datetime,
        "deprecatedSource": V1EventSourceDict,
        "eventTime": datetime.datetime,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "note": str,
        "reason": str,
        "regarding": V1ObjectReferenceDict,
        "related": V1ObjectReferenceDict,
        "reportingController": str,
        "reportingInstance": str,
        "series": V1beta1EventSeriesDict,
        "type": str,
    },
    total=False,
)
