# Code generated by `typeddictgen`. DO NOT EDIT.
"""V1beta1VolumeAttachmentDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V1beta1VolumeAttachmentSpecDict, V1beta1VolumeAttachmentStatusDict

V1beta1VolumeAttachmentDict = TypedDict(
    "V1beta1VolumeAttachmentDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V1beta1VolumeAttachmentSpecDict,
        "status": V1beta1VolumeAttachmentStatusDict,
    },
    total=False,
)
