# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V1beta2RollingUpdateStatefulSetStrategyDict = TypedDict(
    "V1beta2RollingUpdateStatefulSetStrategyDict",
    {
        "partition": int,
    },
    total=False,
)