# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1ReplicaSetDict

V1beta1ReplicaSetListDict = TypedDict(
    "V1beta1ReplicaSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1ReplicaSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
