# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V1beta1StatefulSetDict

V1beta1StatefulSetListDict = TypedDict(
    "V1beta1StatefulSetListDict",
    {
        "apiVersion": str,
        "items": List[V1beta1StatefulSetDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
