# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2alpha1CronJobListDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V1ListMetaDict, V2alpha1CronJobDict

V2alpha1CronJobListDict = TypedDict(
    "V2alpha1CronJobListDict",
    {
        "apiVersion": str,
        "items": List[V2alpha1CronJobDict],
        "kind": str,
        "metadata": V1ListMetaDict,
    },
    total=False,
)
