# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2alpha1CronJobStatusDict generated type."""
import datetime
from typing import TypedDict, List

from kubernetes_typed.client import V1ObjectReferenceDict

V2alpha1CronJobStatusDict = TypedDict(
    "V2alpha1CronJobStatusDict",
    {
        "active": List[V1ObjectReferenceDict],
        "lastScheduleTime": datetime.datetime,
    },
    total=False,
)
