# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2alpha1CronJobDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v1_object_meta import V1ObjectMetaDict
from kubernetes_typed.client.models.v2alpha1_cron_job_spec import V2alpha1CronJobSpecDict
from kubernetes_typed.client.models.v2alpha1_cron_job_status import V2alpha1CronJobStatusDict

V2alpha1CronJobDict = TypedDict(
    "V2alpha1CronJobDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V2alpha1CronJobSpecDict,
        "status": V2alpha1CronJobStatusDict,
    },
    total=False,
)
