# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1MetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta1ExternalMetricStatusDict, V2beta1ObjectMetricStatusDict, V2beta1PodsMetricStatusDict, V2beta1ResourceMetricStatusDict

V2beta1MetricStatusDict = TypedDict(
    "V2beta1MetricStatusDict",
    {
        "external": V2beta1ExternalMetricStatusDict,
        "object": V2beta1ObjectMetricStatusDict,
        "pods": V2beta1PodsMetricStatusDict,
        "resource": V2beta1ResourceMetricStatusDict,
        "type": str,
    },
    total=False,
)
