# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2ObjectMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta2CrossVersionObjectReferenceDict, V2beta2MetricIdentifierDict, V2beta2MetricTargetDict

V2beta2ObjectMetricSourceDict = TypedDict(
    "V2beta2ObjectMetricSourceDict",
    {
        "describedObject": V2beta2CrossVersionObjectReferenceDict,
        "metric": V2beta2MetricIdentifierDict,
        "target": V2beta2MetricTargetDict,
    },
    total=False,
)
