# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

V2beta1ResourceMetricStatusDict = TypedDict(
    "V2beta1ResourceMetricStatusDict",
    {
        "currentAverageUtilization": int,
        "currentAverageValue": str,
        "name": str,
    },
    total=False,
)
