# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2MetricTargetDict generated type."""
from typing import TypedDict

V2beta2MetricTargetDict = TypedDict(
    "V2beta2MetricTargetDict",
    {
        "averageUtilization": int,
        "averageValue": str,
        "type": str,
        "value": str,
    },
    total=False,
)
