# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1MetricSpecDict generated type."""
from typing import TypedDict

from .v2beta1_external_metric_source import V2beta1ExternalMetricSourceDict
from .v2beta1_object_metric_source import V2beta1ObjectMetricSourceDict
from .v2beta1_pods_metric_source import V2beta1PodsMetricSourceDict
from .v2beta1_resource_metric_source import V2beta1ResourceMetricSourceDict

V2beta1MetricSpecDict = TypedDict(
    "V2beta1MetricSpecDict",
    {
        "external": V2beta1ExternalMetricSourceDict,
        "object": V2beta1ObjectMetricSourceDict,
        "pods": V2beta1PodsMetricSourceDict,
        "resource": V2beta1ResourceMetricSourceDict,
        "type": str,
    },
    total=False,
)
