# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2ExternalMetricSourceDict generated type."""
from typing import TypedDict

from .v2beta2_metric_identifier import V2beta2MetricIdentifierDict
from .v2beta2_metric_target import V2beta2MetricTargetDict

V2beta2ExternalMetricSourceDict = TypedDict(
    "V2beta2ExternalMetricSourceDict",
    {
        "metric": V2beta2MetricIdentifierDict,
        "target": V2beta2MetricTargetDict,
    },
    total=False,
)
