# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2ObjectMetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta2CrossVersionObjectReferenceDict, V2beta2MetricIdentifierDict, V2beta2MetricValueStatusDict

V2beta2ObjectMetricStatusDict = TypedDict(
    "V2beta2ObjectMetricStatusDict",
    {
        "current": V2beta2MetricValueStatusDict,
        "describedObject": V2beta2CrossVersionObjectReferenceDict,
        "metric": V2beta2MetricIdentifierDict,
    },
    total=False,
)
