# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V2beta1PodsMetricStatusDict = TypedDict(
    "V2beta1PodsMetricStatusDict",
    {
        "currentAverageValue": str,
        "metricName": str,
        "selector": V1LabelSelectorDict,
    },
    total=False,
)
