# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1ExternalMetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V2beta1ExternalMetricStatusDict = TypedDict(
    "V2beta1ExternalMetricStatusDict",
    {
        "currentAverageValue": str,
        "currentValue": str,
        "metricName": str,
        "metricSelector": V1LabelSelectorDict,
    },
    total=False,
)
