# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1MetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v2beta1_external_metric_status import V2beta1ExternalMetricStatusDict
from kubernetes_typed.client.models.v2beta1_object_metric_status import V2beta1ObjectMetricStatusDict
from kubernetes_typed.client.models.v2beta1_pods_metric_status import V2beta1PodsMetricStatusDict
from kubernetes_typed.client.models.v2beta1_resource_metric_status import V2beta1ResourceMetricStatusDict

V2beta1MetricStatusDict = TypedDict(
    "V2beta1MetricStatusDict",
    {
        "external": V2beta1ExternalMetricStatusDict,
        "object": V2beta1ObjectMetricStatusDict,
        "pods": V2beta1PodsMetricStatusDict,
        "resource": V2beta1ResourceMetricStatusDict,
        "type": str,
    },
    total=False,
)
