# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2HorizontalPodAutoscalerSpecDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client.models.v2beta2_horizontal_pod_autoscaler_behavior import V2beta2HorizontalPodAutoscalerBehaviorDict
from kubernetes_typed.client.models.v2beta2_metric_spec import V2beta2MetricSpecDict
from kubernetes_typed.client.models.v2beta2_cross_version_object_reference import V2beta2CrossVersionObjectReferenceDict

V2beta2HorizontalPodAutoscalerSpecDict = TypedDict(
    "V2beta2HorizontalPodAutoscalerSpecDict",
    {
        "behavior": V2beta2HorizontalPodAutoscalerBehaviorDict,
        "maxReplicas": int,
        "metrics": List[V2beta2MetricSpecDict],
        "minReplicas": int,
        "scaleTargetRef": V2beta2CrossVersionObjectReferenceDict,
    },
    total=False,
)
