# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V2beta2MetricValueStatusDict

V2beta2ResourceMetricStatusDict = TypedDict(
    "V2beta2ResourceMetricStatusDict",
    {
        "current": V2beta2MetricValueStatusDict,
        "name": str,
    },
    total=False,
)
