# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V2beta1ExternalMetricSourceDict = TypedDict(
    "V2beta1ExternalMetricSourceDict",
    {
        "metricName": str,
        "metricSelector": V1LabelSelectorDict,
        "targetAverageValue": str,
        "targetValue": str,
    },
    total=False,
)
