# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict, List

from kubernetes_typed.client import V2beta2CrossVersionObjectReferenceDict, V2beta2MetricSpecDict

V2beta2HorizontalPodAutoscalerSpecDict = TypedDict(
    "V2beta2HorizontalPodAutoscalerSpecDict",
    {
        "maxReplicas": int,
        "metrics": List[V2beta2MetricSpecDict],
        "minReplicas": int,
        "scaleTargetRef": V2beta2CrossVersionObjectReferenceDict,
    },
    total=False,
)
