# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2PodsMetricSourceDict generated type."""
from typing import TypedDict

from kubernetes_typed.client.models.v2beta2_metric_identifier import V2beta2MetricIdentifierDict
from kubernetes_typed.client.models.v2beta2_metric_target import V2beta2MetricTargetDict

V2beta2PodsMetricSourceDict = TypedDict(
    "V2beta2PodsMetricSourceDict",
    {
        "metric": V2beta2MetricIdentifierDict,
        "target": V2beta2MetricTargetDict,
    },
    total=False,
)
