# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1HorizontalPodAutoscalerDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V2beta1HorizontalPodAutoscalerSpecDict, V2beta1HorizontalPodAutoscalerStatusDict

V2beta1HorizontalPodAutoscalerDict = TypedDict(
    "V2beta1HorizontalPodAutoscalerDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V2beta1HorizontalPodAutoscalerSpecDict,
        "status": V2beta1HorizontalPodAutoscalerStatusDict,
    },
    total=False,
)
