# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict

from kubernetes_typed.client import V1ObjectMetaDict, V2beta2HorizontalPodAutoscalerSpecDict, V2beta2HorizontalPodAutoscalerStatusDict

V2beta2HorizontalPodAutoscalerDict = TypedDict(
    "V2beta2HorizontalPodAutoscalerDict",
    {
        "apiVersion": str,
        "kind": str,
        "metadata": V1ObjectMetaDict,
        "spec": V2beta2HorizontalPodAutoscalerSpecDict,
        "status": V2beta2HorizontalPodAutoscalerStatusDict,
    },
    total=False,
)
