# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2HPAScalingPolicyDict generated type."""
from typing import TypedDict

V2beta2HPAScalingPolicyDict = TypedDict(
    "V2beta2HPAScalingPolicyDict",
    {
        "periodSeconds": int,
        "type": str,
        "value": int,
    },
    total=False,
)
