# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1MetricSpecDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V2beta1ExternalMetricSourceDict, V2beta1ObjectMetricSourceDict, V2beta1PodsMetricSourceDict, V2beta1ResourceMetricSourceDict

V2beta1MetricSpecDict = TypedDict(
    "V2beta1MetricSpecDict",
    {
        "external": V2beta1ExternalMetricSourceDict,
        "object": V2beta1ObjectMetricSourceDict,
        "pods": V2beta1PodsMetricSourceDict,
        "resource": V2beta1ResourceMetricSourceDict,
        "type": str,
    },
    total=False,
)
