# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


V2beta2MetricValueStatusDict = TypedDict(
    "V2beta2MetricValueStatusDict",
    {
        "averageUtilization": int,
        "averageValue": str,
        "value": str,
    },
    total=False,
)