# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2MetricStatusDict generated type."""
from typing import TypedDict

from .v2beta2_external_metric_status import V2beta2ExternalMetricStatusDict
from .v2beta2_object_metric_status import V2beta2ObjectMetricStatusDict
from .v2beta2_pods_metric_status import V2beta2PodsMetricStatusDict
from .v2beta2_resource_metric_status import V2beta2ResourceMetricStatusDict

V2beta2MetricStatusDict = TypedDict(
    "V2beta2MetricStatusDict",
    {
        "external": V2beta2ExternalMetricStatusDict,
        "object": V2beta2ObjectMetricStatusDict,
        "pods": V2beta2PodsMetricStatusDict,
        "resource": V2beta2ResourceMetricStatusDict,
        "type": str,
    },
    total=False,
)
