# Code generated by `typeddictgen`. DO NOT EDIT.
from typing import TypedDict


from kubernetes_typed.client import V1LabelSelectorDict

V2beta1PodsMetricSourceDict = TypedDict(
    "V2beta1PodsMetricSourceDict",
    {
        "metricName": str,
        "selector": V1LabelSelectorDict,
        "targetAverageValue": str,
    },
    total=False,
)