# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2HPAScalingRulesDict generated type."""
from typing import TypedDict, List

from kubernetes_typed.client import V2beta2HPAScalingPolicyDict

V2beta2HPAScalingRulesDict = TypedDict(
    "V2beta2HPAScalingRulesDict",
    {
        "policies": List[V2beta2HPAScalingPolicyDict],
        "selectPolicy": str,
        "stabilizationWindowSeconds": int,
    },
    total=False,
)
