# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta1PodsMetricStatusDict generated type."""
from typing import TypedDict

from kubernetes_typed.client import V1LabelSelectorDict

V2beta1PodsMetricStatusDict = TypedDict(
    "V2beta1PodsMetricStatusDict",
    {
        "currentAverageValue": str,
        "metricName": str,
        "selector": V1LabelSelectorDict,
    },
    total=False,
)
