# Code generated by `typeddictgen`. DO NOT EDIT.
"""V2beta2MetricSpecDict generated type."""
from typing import TypedDict

from .v2beta2_external_metric_source import V2beta2ExternalMetricSourceDict
from .v2beta2_object_metric_source import V2beta2ObjectMetricSourceDict
from .v2beta2_pods_metric_source import V2beta2PodsMetricSourceDict
from .v2beta2_resource_metric_source import V2beta2ResourceMetricSourceDict

V2beta2MetricSpecDict = TypedDict(
    "V2beta2MetricSpecDict",
    {
        "external": V2beta2ExternalMetricSourceDict,
        "object": V2beta2ObjectMetricSourceDict,
        "pods": V2beta2PodsMetricSourceDict,
        "resource": V2beta2ResourceMetricSourceDict,
        "type": str,
    },
    total=False,
)
