# Code generated by `typeddictgen`. DO NOT EDIT.
"""VersionInfoDict generated type."""
from typing import TypedDict

VersionInfoDict = TypedDict(
    "VersionInfoDict",
    {
        "buildDate": str,
        "compiler": str,
        "gitCommit": str,
        "gitTreeState": str,
        "gitVersion": str,
        "goVersion": str,
        "major": str,
        "minor": str,
        "platform": str,
    },
    total=False,
)
