from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class ExtensionsV1beta1AllowedFlexVolume:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, driver: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def driver(self): ...
    @driver.setter
    def driver(self, driver: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
