from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class ExtensionsV1beta1IngressRule:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, host: Optional[Any] = ..., http: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def host(self): ...
    @host.setter
    def host(self, host: Any) -> None: ...
    @property
    def http(self): ...
    @http.setter
    def http(self, http: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
