from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1CustomResourceDefinitionVersion:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, additional_printer_columns: Optional[Any] = ..., name: Optional[Any] = ..., schema: Optional[Any] = ..., served: Optional[Any] = ..., storage: Optional[Any] = ..., subresources: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def additional_printer_columns(self): ...
    @additional_printer_columns.setter
    def additional_printer_columns(self, additional_printer_columns: Any) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name: Any) -> None: ...
    @property
    def schema(self): ...
    @schema.setter
    def schema(self, schema: Any) -> None: ...
    @property
    def served(self): ...
    @served.setter
    def served(self, served: Any) -> None: ...
    @property
    def storage(self): ...
    @storage.setter
    def storage(self, storage: Any) -> None: ...
    @property
    def subresources(self): ...
    @subresources.setter
    def subresources(self, subresources: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
