from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1Event:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, action: Optional[Any] = ..., api_version: Optional[Any] = ..., count: Optional[Any] = ..., event_time: Optional[Any] = ..., first_timestamp: Optional[Any] = ..., involved_object: Optional[Any] = ..., kind: Optional[Any] = ..., last_timestamp: Optional[Any] = ..., message: Optional[Any] = ..., metadata: Optional[Any] = ..., reason: Optional[Any] = ..., related: Optional[Any] = ..., reporting_component: Optional[Any] = ..., reporting_instance: Optional[Any] = ..., series: Optional[Any] = ..., source: Optional[Any] = ..., type: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def action(self): ...
    @action.setter
    def action(self, action: Any) -> None: ...
    @property
    def api_version(self): ...
    @api_version.setter
    def api_version(self, api_version: Any) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count: Any) -> None: ...
    @property
    def event_time(self): ...
    @event_time.setter
    def event_time(self, event_time: Any) -> None: ...
    @property
    def first_timestamp(self): ...
    @first_timestamp.setter
    def first_timestamp(self, first_timestamp: Any) -> None: ...
    @property
    def involved_object(self): ...
    @involved_object.setter
    def involved_object(self, involved_object: Any) -> None: ...
    @property
    def kind(self): ...
    @kind.setter
    def kind(self, kind: Any) -> None: ...
    @property
    def last_timestamp(self): ...
    @last_timestamp.setter
    def last_timestamp(self, last_timestamp: Any) -> None: ...
    @property
    def message(self): ...
    @message.setter
    def message(self, message: Any) -> None: ...
    @property
    def metadata(self): ...
    @metadata.setter
    def metadata(self, metadata: Any) -> None: ...
    @property
    def reason(self): ...
    @reason.setter
    def reason(self, reason: Any) -> None: ...
    @property
    def related(self): ...
    @related.setter
    def related(self, related: Any) -> None: ...
    @property
    def reporting_component(self): ...
    @reporting_component.setter
    def reporting_component(self, reporting_component: Any) -> None: ...
    @property
    def reporting_instance(self): ...
    @reporting_instance.setter
    def reporting_instance(self, reporting_instance: Any) -> None: ...
    @property
    def series(self): ...
    @series.setter
    def series(self, series: Any) -> None: ...
    @property
    def source(self): ...
    @source.setter
    def source(self, source: Any) -> None: ...
    @property
    def type(self): ...
    @type.setter
    def type(self, type: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
