from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1Handler:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, _exec: Optional[Any] = ..., http_get: Optional[Any] = ..., tcp_socket: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def http_get(self): ...
    @http_get.setter
    def http_get(self, http_get: Any) -> None: ...
    @property
    def tcp_socket(self): ...
    @tcp_socket.setter
    def tcp_socket(self, tcp_socket: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
