from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1PodSecurityContext:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, fs_group: Optional[Any] = ..., run_as_group: Optional[Any] = ..., run_as_non_root: Optional[Any] = ..., run_as_user: Optional[Any] = ..., se_linux_options: Optional[Any] = ..., supplemental_groups: Optional[Any] = ..., sysctls: Optional[Any] = ..., windows_options: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def fs_group(self): ...
    @fs_group.setter
    def fs_group(self, fs_group: Any) -> None: ...
    @property
    def run_as_group(self): ...
    @run_as_group.setter
    def run_as_group(self, run_as_group: Any) -> None: ...
    @property
    def run_as_non_root(self): ...
    @run_as_non_root.setter
    def run_as_non_root(self, run_as_non_root: Any) -> None: ...
    @property
    def run_as_user(self): ...
    @run_as_user.setter
    def run_as_user(self, run_as_user: Any) -> None: ...
    @property
    def se_linux_options(self): ...
    @se_linux_options.setter
    def se_linux_options(self, se_linux_options: Any) -> None: ...
    @property
    def supplemental_groups(self): ...
    @supplemental_groups.setter
    def supplemental_groups(self, supplemental_groups: Any) -> None: ...
    @property
    def sysctls(self): ...
    @sysctls.setter
    def sysctls(self, sysctls: Any) -> None: ...
    @property
    def windows_options(self): ...
    @windows_options.setter
    def windows_options(self, windows_options: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
