from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1alpha1Policy:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, level: Optional[Any] = ..., stages: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def level(self): ...
    @level.setter
    def level(self, level: Any) -> None: ...
    @property
    def stages(self): ...
    @stages.setter
    def stages(self, stages: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
