from kubernetes.client.configuration import Configuration as Configuration
from typing import Any, Optional

class V1alpha1Webhook:
    openapi_types: Any = ...
    attribute_map: Any = ...
    local_vars_configuration: Any = ...
    discriminator: Any = ...
    def __init__(self, client_config: Optional[Any] = ..., throttle: Optional[Any] = ..., local_vars_configuration: Optional[Any] = ...) -> None: ...
    @property
    def client_config(self): ...
    @client_config.setter
    def client_config(self, client_config: Any) -> None: ...
    @property
    def throttle(self): ...
    @throttle.setter
    def throttle(self, throttle: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
