# Code generated by `stubgen`. DO NOT EDIT.
from kubernetes.client.configuration import Configuration as Configuration
from kubernetes.config import kube_config as kube_config

DEFAULT_E2E_HOST: str

def get_e2e_configuration(): ...
