# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete

class PortServer:
    port: Incomplete
    server: Incomplete
    thread: Incomplete
    def __init__(self, port) -> None: ...
    def handler(self, request, address, server) -> None: ...
