# Code generated by `stubgen`. DO NOT EDIT.
from typing import Any

class PortServer:
    port: Any
    server: Any
    thread: Any
    def __init__(self, port) -> None: ...
    def handler(self, request, address, server) -> None: ...
