# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from kubernetes.client import api_client as api_client
from kubernetes.client.api import batch_v1_api as batch_v1_api
from kubernetes.e2e_test import base as base

class TestClientBatch(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    def test_job_apis(self) -> None: ...
