# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from . import DynamicClient as DynamicClient
from kubernetes.client import api_client as api_client
from kubernetes.e2e_test import base as base

class TestDiscoverer(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None: ...
    def test_init_cache_from_file(self) -> None: ...
