# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete

class OpenApiException(Exception): ...

class ApiTypeError(OpenApiException, TypeError):
    path_to_item: Incomplete
    valid_classes: Incomplete
    key_type: Incomplete
    def __init__(self, msg, path_to_item: Incomplete | None = None, valid_classes: Incomplete | None = None, key_type: Incomplete | None = None) -> None: ...

class ApiValueError(OpenApiException, ValueError):
    path_to_item: Incomplete
    def __init__(self, msg, path_to_item: Incomplete | None = None) -> None: ...

class ApiKeyError(OpenApiException, KeyError):
    path_to_item: Incomplete
    def __init__(self, msg, path_to_item: Incomplete | None = None) -> None: ...

class ApiException(OpenApiException):
    status: Incomplete
    reason: Incomplete
    body: Incomplete
    headers: Incomplete
    def __init__(self, status: Incomplete | None = None, reason: Incomplete | None = None, http_resp: Incomplete | None = None) -> None: ...

def render_path(path_to_item): ...
