# Code generated by `stubgen`. DO NOT EDIT.
from .config_exception import ConfigException as ConfigException
from .incluster_config import load_incluster_config as load_incluster_config
from .kube_config import KUBE_CONFIG_DEFAULT_LOCATION as KUBE_CONFIG_DEFAULT_LOCATION, list_kube_config_contexts as list_kube_config_contexts, load_kube_config as load_kube_config, load_kube_config_from_dict as load_kube_config_from_dict, new_client_from_config as new_client_from_config

def load_config(**kwargs) -> None: ...
