# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from .dateutil import TimezoneInfo as TimezoneInfo, UTC as UTC, format_rfc3339 as format_rfc3339, parse_rfc3339 as parse_rfc3339

class DateUtilTest(unittest.TestCase):
    def test_parse_rfc3339(self) -> None: ...
    def test_format_rfc3339(self) -> None: ...
