# Code generated by `stubgen`. DO NOT EDIT.
from .config_exception import ConfigException as ConfigException
from _typeshed import Incomplete

class ExecProvider:
    api_version: Incomplete
    args: Incomplete
    env: Incomplete
    def __init__(self, exec_config) -> None: ...
    def run(self, previous_response: Incomplete | None = None): ...
