# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete

class Config:
    jitter_factor: float
    lock: Incomplete
    lease_duration: Incomplete
    renew_deadline: Incomplete
    retry_period: Incomplete
    onstarted_leading: Incomplete
    onstopped_leading: Incomplete
    def __init__(self, lock, lease_duration, renew_deadline, retry_period, onstarted_leading, onstopped_leading) -> None: ...
    def on_stoppedleading_callback(self) -> None: ...
