# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete
from kubernetes import client as client, config as config

candidate_id: Incomplete
lock_name: str
lock_namespace: str

def example_func() -> None: ...
