# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from . import electionconfig as electionconfig, leaderelection as leaderelection
from .leaderelectionrecord import LeaderElectionRecord as LeaderElectionRecord
from _typeshed import Incomplete
from kubernetes.client.rest import ApiException as ApiException

thread_lock: Incomplete

class LeaderElectionTest(unittest.TestCase):
    def test_simple_leader_election(self) -> None: ...
    def test_leader_election(self) -> None: ...
    def test_Leader_election_with_renew_deadline(self) -> None: ...
    def assert_history(self, history, expected) -> None: ...

class MockResourceLock:
    leader_record: Incomplete
    renew_count: int
    renew_count_max: int
    name: Incomplete
    namespace: Incomplete
    identity: Incomplete
    lock: Incomplete
    on_create: Incomplete
    on_update: Incomplete
    on_change: Incomplete
    on_try_update: Incomplete
    def __init__(self, name, namespace, identity, shared_lock, on_create: Incomplete | None = None, on_update: Incomplete | None = None, on_change: Incomplete | None = None, on_try_update: Incomplete | None = None) -> None: ...
    def get(self, name, namespace): ...
    def create(self, name, namespace, election_record): ...
    def update(self, name, namespace, updated_record): ...
