# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete

class LeaderElectionRecord:
    holder_identity: Incomplete
    lease_duration: Incomplete
    acquire_time: Incomplete
    renew_time: Incomplete
    def __init__(self, holder_identity, lease_duration, acquire_time, renew_time) -> None: ...
