# Code generated by `stubgen`. DO NOT EDIT.
from .config_exception import ConfigException as ConfigException
from typing import Any

class ExecProvider:
    api_version: Any
    args: Any
    env: Any
    def __init__(self, exec_config) -> None: ...
    def run(self, previous_response: Any | None = ...): ...
