# Code generated by `stubgen`. DO NOT EDIT.
from .config_exception import ConfigException as ConfigException
from kubernetes.client import Configuration as Configuration
from typing import Any, Optional

SERVICE_HOST_ENV_NAME: str
SERVICE_PORT_ENV_NAME: str
SERVICE_TOKEN_FILENAME: str
SERVICE_CERT_FILENAME: str

class InClusterConfigLoader:
    def __init__(self, token_filename: Any, cert_filename: Any, try_refresh_token: bool = ..., environ: Any = ...) -> None: ...
    def load_and_set(self, client_configuration: Optional[Any] = ...) -> None: ...

def load_incluster_config(client_configuration: Optional[Any] = ..., try_refresh_token: bool = ...) -> None: ...
