# Code generated by `stubgen`. DO NOT EDIT.
from kubernetes import client as client, config as config
from typing import Any

candidate_id: Any
lock_name: str
lock_namespace: str

def example_func() -> None: ...
