# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from . import electionconfig as electionconfig, leaderelection as leaderelection
from .leaderelectionrecord import LeaderElectionRecord as LeaderElectionRecord
from kubernetes.client.rest import ApiException as ApiException
from typing import Any

thread_lock: Any

class LeaderElectionTest(unittest.TestCase):
    def test_simple_leader_election(self) -> None: ...
    def test_leader_election(self) -> None: ...
    def test_Leader_election_with_renew_deadline(self) -> None: ...
    def assert_history(self, history, expected) -> None: ...

class MockResourceLock:
    leader_record: Any
    renew_count: int
    renew_count_max: int
    name: Any
    namespace: Any
    identity: Any
    lock: Any
    on_create: Any
    on_update: Any
    on_change: Any
    on_try_update: Any
    def __init__(self, name, namespace, identity, shared_lock, on_create: Any | None = ..., on_update: Any | None = ..., on_change: Any | None = ..., on_try_update: Any | None = ...) -> None: ...
    def get(self, name, namespace): ...
    def create(self, name, namespace, election_record): ...
    def update(self, name, namespace, updated_record): ...
