# Code generated by `stubgen`. DO NOT EDIT.
from typing import Any

class LeaderElectionRecord:
    holder_identity: Any
    lease_duration: Any
    acquire_time: Any
    renew_time: Any
    def __init__(self, holder_identity, lease_duration, acquire_time, renew_time) -> None: ...
