# Code generated by `stubgen`. DO NOT EDIT.
import unittest
from .ws_client import get_websocket_url as get_websocket_url

class WSClientTest(unittest.TestCase):
    def test_websocket_client(self) -> None: ...
