# Code generated by `stubgen`. DO NOT EDIT.
from _typeshed import Incomplete
from kubernetes import client as client

UPPER_FOLLOWED_BY_LOWER_RE: Incomplete
LOWER_OR_NUM_FOLLOWED_BY_UPPER_RE: Incomplete

def create_from_yaml(k8s_client, yaml_file: Incomplete | None = None, yaml_objects: Incomplete | None = None, verbose: bool = False, namespace: str = 'default', **kwargs): ...
def create_from_dict(k8s_client, data, verbose: bool = False, namespace: str = 'default', **kwargs): ...
def create_from_yaml_single_item(k8s_client, yml_object, verbose: bool = False, **kwargs): ...

class FailToCreateError(Exception):
    api_exceptions: Incomplete
    def __init__(self, api_exceptions) -> None: ...
